### ISSUE TITLE
Regenerate URL rewrites -- Information needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#1]
# Background

Question from Support issue:

URL rewrites have been broken or deleted.

Now all products URLs are displayed as http://www.example.com/catalog/category/id/6

How to regenerate URL rewrites?

Answer
Unlike Magento 1, Magento 2 does not have a separate URL rewrite Indexer.

In order to create a single URL rewrite, please refer to http://docs.magento.com/m2/ce/user_guide/marketing/url-rewrite-create.html

There is a workaround that allows to quickly fix URL rewrites for all products simultaneously.

Steps:
Open Admin > Catalog > Products
Select All products for which you want to update URL rewrites
In Actions dropdown, select Update Attributes to perform mass update
Switch to Websites tab
In 'Add Product To Websites' section select all websites for which you want to restore URL rewrites. 
Note that all selected products will be re-added to the selected websites and URL rewrites will be regenerated.

## Affected docs
https://docs.magento.com/m2/ce/user_guide/stores/admin-actions-control.html
https://docs.magento.com/m2/ce/user_guide/marketing/url-rewrite.html

- [x] Open Source
- [x] Commerce
- [x] B2B

#  Proposed solution

Add the workaround information to regenerate URL rewrites to one of the affected topics

**Comment by hickskenh** [comment]
Adding the Multiple URL Rewrites topic with the workaround information added.  first adding to 2.3, when approved, will add to 2.4 also.
