### ISSUE TITLE
B2B company credit discussion incomplete

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#10]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/b2b/user_guide/sales/credit-company.html

## Description
The discussion of company credit needs clarification and additional information. This observation was made by a developer translating the docs into German, where the term "credit" can be translated in my ways. 

## Affected Guides

- [ ] Open Source
- [ ] Commerce
- [x] B2B

## Possible solutions

Something like this can help?

The limit value of credit granted by the seller to the purchasing company is to enable agility in PO purchases, if necessary
The value of the credit is defined by the seller for each company, and the credit possibility for the companies to make the purchase without payment at the moment, accumulating several buy for later payment according to the negotiation that this one has with the seller.

## Additional information

Another discussion in the doc set that might be useful: https://devdocs.magento.com/guides/v2.3/b2b/credit-manage.html

Ticket created at Imagine 2019 Contribution Day.

**Comment by dobooth** [comment]
I think "credit" in the scope of an online store is clear. The word 'credit' has many definitions in English as well. Happy to reopen if this is causing confusion.
