### ISSUE TITLE
Feedback on page: /catalog/product-create-configurable.html

### ISSUE THREAD

**Issue by kokitamoto** [magento/merchdocs#1006]
In Step 4. 
No.6 and No.8 is the same. 
Should be deleted one line

[To feature the product in the list of new products, select the Set Product as New checkbox.]

![image](https://user-images.githubusercontent.com/40748643/105658359-aacf7880-5f09-11eb-970d-6bed52330e61.png)

**Comment by dineshvb** [comment]
@magento I am working on this
