### ISSUE TITLE
Apply a special price to multiple products - Open Source only

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#1010]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/product-price-special.html#apply-a-special-price-to-multiple-products

## Description

The functionality described in "Apply a special price to multiple products" is only applicable to Magento Open Source.

In Magento Commerce, setting special price to date and from date must be done via scheduled updates as described here.

This was confirmed by PO in MC-40627

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Possible solutions

Please update our user guide and consider adding the "Magento Open Source only" tag/banner to Apply a special price to multiple products

## Additional information

Created to replace DOC-252

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
this appears to be completed. https://docs.magento.com/user-guide/catalog/product-price-special.html#apply-a-special-price-to-multiple-products
