### ISSUE TITLE
Revise suggestion regarding use of allow_url_fopen due to possible security risk

### ISSUE THREAD

**Issue by akkaweb** [magento/merchdocs#1014]
One of the requirements for reCAPTCHA to work in Magento is to enable **allow_url_fopen**, but that is a security risk. The reCAPTCHA library allows the use of cURL and Socket for servers where that is not enabled. It is just a concern that Magento Docs would suggest enabling allow_url_fopen in order to use reCAPTCHA. I will look into submitting a patch.

Page Link: https://docs.magento.com/user-guide/configuration/security/google-recaptcha-admin.html

**Comment by jcalcaben** [comment]
@akkaweb please add a link to the PR that adds this patch as a comment so we will know when we can make the doc changes.

**Comment by bdenham** [comment]
@akkaweb what's the status on the patch for this?

**Comment by bdenham** [comment]
Waiting for patch
