### ISSUE TITLE
Clarify Event Ticker information (enabling/disabling)

### ISSUE THREAD

**Issue by hickskenh** [magento/merchdocs#105]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/marketing/event-ticker.html

## Description

The topic refers to "if the product page ticker is enabled", but i found no info on enabling the ticker.  

## Possible solutions

I think the ticker is part of the carousel function/template.  May just need to change wording, or may need to add more information in the carousel topic about the ticker.

**Comment by danidelcar** [comment]
@leslietilling @hickskenh can this issue be groomed so can be open to community for work?
