### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by braders** [magento/merchdocs#1055]
In this topic:
https://docs.magento.com/user-guide/marketing/google-tag-manager.html

The following text:

>  * The Overwrite option should be selected for the new container.
>  * The Merge option should be selected is you are using an existing container.

would be better worded as:

>  * The Overwrite option should be selected for a new container.
>  * The Merge option should be selected if you are using an existing container.

This is under "Step 2. Configure Your Google Tag Manager Account"

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
Changes were made earlier.
