### ISSUE TITLE
Update SaaS Services Page with New Fields

### ISSUE THREAD

**Issue by vmalyk** [magento/merchdocs#1057]
In this topic:
https://docs.magento.com/user-guide/configuration/services/saas.html

Configuration fields - It's outdated and in SAAS Services version 1.1.0. You need to set up 4 fields:
- Production Api Key
- **Production Private Key** (It's new)
- Sandbox Api Key
-  **Sandbox Private Key**  (It's new)

it's used for Magento Recommendations since 3.0.0. 

In addition, will be great to add information how to add keys and notice about required saving Private keys after generation.

**Comment by erikmarr** [comment]
@vmalyk thanks for the feedback! We have updated the topic to reflect the new fields.

**Comment by erikmarr** [comment]
Updated documentation.
