### ISSUE TITLE
Adding a block to the banner documentation

### ISSUE THREAD

**Issue by qaniel** [magento/merchdocs#1065]
Feedback on page: /cms/page-builder-media-slider.html

As the documentation says on [Complex content in settings](https://docs.magento.com/user-guide/cms/page-builder-media-slider.html#complex-content-in-the-settings) point **6** in the hint section
![Screen Shot 2021-02-23 at 09 32 44](https://user-images.githubusercontent.com/26260746/108866745-1749a000-75ba-11eb-9d43-c042a7b785b4.png)
The Magento 2.4 page builder does not support or shows any functionality to add blocks into the slides, this result confusing and misguiding when evaluating the slider functionality. It should be removed or clarify how to add a block on a slide banner.

Or maybe I missed where to add it?

EDIT: I just found the same hint on the Banner documentation... is this a case of copypasta?

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
