### ISSUE TITLE
Provide example for base currency verification

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1069]
Feedback on page: /reports/advanced-reporting.html

https://docs.magento.com/user-guide/reports/advanced-reporting.html#verify-single-base-currency

Suggest providing a Mysql query the customer could use to determine if multiple base currencies are in use:
``` select distinct base_currency_code from sales_order;```

**Comment by erikmarr** [comment]
Discussed with internal dev. I'll update the docs to include this SQL query but mention how the query might not work if you are a B2C vs B2B merchant due to possible differences in your data structure.

**Comment by erikmarr** [comment]
Updated documentation:
https://github.com/magento-commerce/merchdocs/pull/20
