### ISSUE TITLE
Add RMA how-to instructions to Returns section topics

### ISSUE THREAD

**Issue by shrielenee** [magento/merchdocs#1089]
There is a bevy of information about what RMAs are, what their flow is, etc. but we need explicit, simple information about how to create an RMA.

https://docs.magento.com/user-guide/sales/returns.html

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by ZhovnirMaria** [comment]
Hi, @dobooth!
Would you be so kind, to check my PR? Thank you!
https://github.com/magento/merchdocs/pull/1183
