### ISSUE TITLE
Custom admin url naming

### ISSUE THREAD

**Issue by hguthrie** [magento/merchdocs#1098]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html

## Description

Received Slack message:

> no where is mentioned the rules & restriction to set up the admin frontname/url. Whereas in the cloud merchant can't include dash(-) in the frontname, it throws error. Request you to kindly check and update the doc for merchants convenience.

> When creating an Admin URL...if you try to use hyphens it will fail but there's no requirement specified on the docs
the same thing occurs if you set Custom Admin Path in the admin configuration with a hyphen

The cloud guide references the custom admin url in the following topic:
https://devdocs.magento.com/cloud/env/environment-vars_magento.html#admin-url

Example error when using a hyphen:

> Invalid backend frontname `custom-admin-name`

## Possible solutions

Perhaps both topics need to provide guidance for naming the URLs.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by atwixfirster** [comment]
@EvheniiaKolkhiieva please note that this issue ties to DevDocs repository - https://github.com/magento/devdocs

PR with the explanations should be added into https://github.com/magento/devdocs/blob/master/src/cloud/env/environment-vars_magento.md

Thank you!

**Comment by EvheniiaKolkhiieva** [comment]
Hello, @hguthrie 

Fix for this issue has been implemented. You can see the changes here - https://github.com/magento/devdocs/pull/8858

Thanks!

**Comment by hguthrie** [comment]
@atwixfirster  @EvheniiaKolkhiieva  Although that fix in DevDocs was good, it may not completely address this issue. The fix in DevDocs was only made to the Cloud guide. Is it only necessary to mention it there for Cloud and not for Magento Admin URL naming in general or for on-premises? Or provide a specific note here in the User guide that, for Cloud, it is controlled using an environment variable? I want to make sure this correction is thorough and clear for the reader.

**Comment by hguthrie** [comment]
Merged in DevDocs. Thanks! https://github.com/magento/devdocs/pull/8858

**Comment by atwixfirster** [comment]
Hi, @hguthrie!

> Is it only necessary to mention it there for Cloud and not for Magento Admin URL naming in general or for on-premises? Or provide a specific note here in the User guide that, for Cloud, it is controlled using an environment variable? I want to make sure this correction is thorough and clear for the reader.

Answering on your questions I would like to say:
- we need to add a notice to "`Method 1: Change from the Magento Admin`" of [Using a Custom Admin URL](https://docs.magento.com/user-guide/stores/store-urls-custom-admin.html) that admin user may specify a custom admin path via `ADMIN_URL` Cloud variable in Cloud UI (from the technical side when a custom admin path is specified in `ADMIN_URL` Cloud variable then this value is added into `app/etc/env.php`. See "`Method 2: Change the Admin Path from the server command line`").
- additionally we can add the information how to set a custom admin path via `bin/magento config:set` Magento commands. 

If you are okay with my suggestions @EvheniiaKolkhiieva  will create a new PR for that. Please let us know if we can use this issue for reference?

Thank you!
