### ISSUE TITLE
Temporary Admin Access - New Feature

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#11]
Created issue at 2019 Imagine Contribution Day. This will move to Merchdocs when that repo is ready. 

# New feature request

At Imagine 2019 Contribution Day, there is a Security issue for creating options and code for configuring temp admin access. Merchants sometimes create accounts for extension developers/partners/etc to access and test issues. They may forget to delete the account, leaving it as a potential access point if the credentials are simple.

## Description

Content in Admin:

1. Create User.
2. Admin can set expiration date on user acct.
3. CRON job runs every hour looking for active expired accounts.
4. If one is found, removes the date and sets as inactive.
5. If you edit the user account in the Admin, the status is inactive without an expiration date.
6. To reuse, the account can be set "active" with a new expiration date.

Issue https://github.com/magento/magento2/issues/22833
PR https://github.com/magento/magento2/pull/22837

## Additional information

The additional feature and screens only available when the PR is merged. Watch PR https://github.com/magento/magento2/pull/22837 for updates!

**Comment by hickskenh** [comment]
Transferred to Internal issue 1

**Comment by hickskenh** [comment]
re-opening this issue as part of 2.4 release.  related issue in Merchdocs Internal repo is closed.  Expiration date field added to User Account Information screen in 2.4. Do not see it in a 2.3.5 instance.

**Comment by hickskenh** [comment]
Need to update system/permissions-users-all.md with screen shot and expiration text. https://docs.magento.com/m2/ee/user_guide/system/permissions-users-all.html

**Comment by hickskenh** [comment]
Merged pull request #453
