### ISSUE TITLE
UPS. Access License Number, clarification

### ISSUE THREAD

**Issue by EvheniiaKolkhiieva** [magento/merchdocs#1102]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/shipping/ups.html

## Description
It is necessary to make edits to the UPS user guide. 
Corrections concern the name and symbols value of the Access License Number described in https://www.ups.com/media/en/UPS_dev_kit_user_guide.pdf on the **12th** page

Acceptance criteria:
1. Change the 'Access License Number' to the 'Access Key' title
2. Set the required value of the of the Access Key to 16 symbols 

## Magento release version

- [x]  2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Additional information
![image](https://user-images.githubusercontent.com/78729171/112290137-9a344800-8c97-11eb-936e-9c410202818e.png)

![image](https://user-images.githubusercontent.com/78729171/112290195-a6200a00-8c97-11eb-8559-75414a08bcf8.png)

**Comment by ZhovnirMaria** [comment]
@magento_cloud I am working on this

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by ZhovnirMaria** [comment]
@magento add to contributors team

**Comment by ZhovnirMaria** [comment]
@magento add to contributors team

**Comment by ZhovnirMaria** [comment]
@magento I am working on this
