### ISSUE TITLE
Allow Reorders from customer account

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1103]
# Topic clarification/correction request

## Topic Link
https://docs.magento.com/user-guide/sales/reorders-allow.html

## Description

The "Allow Reorders" instruction from Magento User Guide contains only a screenshot for creating Reorders from the admin panel.
 It is would be good to add a screenshot for creating Reorders from the customer storefront.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Additional information
![image](https://user-images.githubusercontent.com/79835574/112303995-a2937f80-8ca5-11eb-859d-09afd4eef6b1.png)
![image](https://user-images.githubusercontent.com/79835574/112304043-b17a3200-8ca5-11eb-8670-910ee9e1d1d5.png)

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
@magento add to contributors team

**Comment by EvheniiaKolkhiieva** [comment]
@magento add to contributors team

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
