### ISSUE TITLE
Update user guide to include information about sitemaps and robots.txt for multistore configuration

### ISSUE THREAD

**Issue by Ovidijus-emotion** [magento/merchdocs#1104]
There is no information on sitemaps and robots.txt for multistore configuration.
@magento I am working on this

Link: https://docs.magento.com/user-guide/marketing/sitemap-xml.html

**Comment by dobooth** [comment]
@Ovidijus-emotion Did you want to work on this issue?

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
