### ISSUE TITLE
Describe 'Image Detail' for products 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1108]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/product-images-and-video.html

## Description

Describe 'Image Detail' topic for products settings admin page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Additional information
![image](https://user-images.githubusercontent.com/79835574/112451889-aa632a80-8d5e-11eb-9a33-3c8875dc4767.png)

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
this appears to be completed.  https://docs.magento.com/user-guide/catalog/product-images-and-video.html
