### ISSUE TITLE
Speed up local building by providing option to disable link checker

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#111]
# New feature request

## Description

Hi there! As a feature/dev request for doc authors, I think it would be nice to provide an option to the `rake preview` task (and its subtasks) and be able to disable the link checking on each incremental Jekyll build. Currently the link checking takes the longest, and for me locally when building just one version of the docs (e.g. the CE docs), takes about a minute to build. A majority of this time seems to be spent on checking the validity of links.

## Expected result

While link checking is super useful, when I'm in content-authoring mode, I don't really care about the links, I care more about a tight feedback loop between authoring content, saving it, having Jekyll rebuild, and seeing the result in my browser locally.

Then, before I push up my changes to a branch to start a pull request and kick off a review, I could run the `preview` task with link checking to make sure I didn't introduce any broken links.

## Benefits

Content authors can iterate more quickly when writing documentation locally.

## Possible solutions

Perhaps adding a flag or option to the `rake` tasks? Would a CLI flag like `--no-link-check` or `--disable-link-check` be an option?

**Comment by hickskenh** [comment]
@filmaj Thank you for your submission. you can disable link checker in your `_config.yml` file by setting `check_links: false`. Then, you can re-enable the link checking to verify your branch before submitting a PR. I will have to get additional feedback from the team about adding a command that applies only to incremental builds.

**Comment by filmaj** [comment]
Nice, thanks! I will try that!
