### ISSUE TITLE
Expand catalog and products viewed compared topics

### ISSUE THREAD

**Issue by ddrt** [magento/merchdocs#1117]
Both of these links lack all available configurations and options that are housed at the default site scope:

- https://docs.magento.com/user-guide/configuration/catalog/catalog.html
- https://docs.magento.com/user-guide/v2.3/marketing/products-viewed-compared.html

**Missing instructions for:** 

1. Synchronize widget products with backend storage
2. Lifetime of products in Recently Viewed Widget
3. Lifetime of products in Recently Compared Widget

Here is a stack exchange question for this topic (Age: 2 years and 3 months)

- https://magento.stackexchange.com/questions/230345/core-configuration-of-recently-viewed-compared-products-synchronize-widget-pro

As a larger note: Please ensure that diligence is completed for all potential site scopes specifically (and especially) default since it does house settings not seen on drilled-down views.

Also, after reading the stack exchange question, the wording around these settings (and  a lot of other settings) is obtuse. More effort should be put into explaining features, settings, and their expected outcomes, in ways that the majority can comprehend.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
