### ISSUE TITLE
Describe the Gift Card functionality 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1118]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/customers/account-dashboard-gift-cards.html

## Description

Describe the "Redeem Gift Card" functionality for the Magento User Account

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Additional information

<img width="1409" alt="Store Credit 2021-03-31 11-19-38" src="https://user-images.githubusercontent.com/79835574/113113543-16d4a280-9213-11eb-9e0e-04bc0d871aa9.png">

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by bdenham** [comment]
Hi @ZhovnirMaria I'm not sure what value the screen shot has for this topic. Can you explain your reasoning a bit.

**Comment by ZhovnirMaria** [comment]
Hi @bdenham! This screenshot was added to show what I was working on. Thank you!

**Comment by hickskenh** [comment]
this appears to be completed. https://docs.magento.com/user-guide/customers/account-dashboard-gift-cards.html
