### ISSUE TITLE
Add a new page about the "Recently Ordered Products" functionality 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1120]
# New topic request

## Description

Add a new page about the "Recently Ordered Products" functionality 

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Content checklist

- [x] The topic provides an explanation of how the "Recently Ordered" functionality works.
- [x] The topic contains examples that show how the "Recently Ordered" functionality looks like and works.

## Additional information/resources
<img width="347" alt="Bags - Gear 2021-03-31 16-25-01" src="https://user-images.githubusercontent.com/79835574/113152623-fb7f8c80-923e-11eb-9871-221466ba25b7.png">

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by bdenham** [comment]
Hi @ZhovnirMaria, thanks for thinking about this, but as a best practice, we don't want to document the UI items that are common and self-explanatory. But continue to look for items that are less common, and need better explanations. Thanks.
