### ISSUE TITLE
Describe customer steps to allow remote shopping assistance 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1122]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/customers/login-as-customer.html

## Description

Describe customer steps to allow remote shopping assistance on the storefront

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
this appears to be completed. https://docs.magento.com/user-guide/customers/login-as-customer.html
