### ISSUE TITLE
Describe sign out of the customer account

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1124]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/customers/customer-sign-in.html?itm_source=merchdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=sig

## Description

Describe sign out of the customer account

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by bdenham** [comment]
Hi @ZhovnirMaria, for this one, we don't need to describe the basic functionality. These things are addressed elsewhere in the docs as well as other guides.
