### ISSUE TITLE
Supplement the "Actions by grid" block for the "Actions Control" page

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1129]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/stores/admin-actions-control.html

## Description

Supplement the "Actions by grid" block for the "Actions Control" page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
This appears to be completed.  https://docs.magento.com/user-guide/stores/admin-actions-control.html
