### ISSUE TITLE
Feedback on page: /system/data-attributes-product.html

### ISSUE THREAD

**Issue by rahimimo** [magento/merchdocs#1136]
Since this is called a product attribute reference It is expected it contains all the attributes. Although it says 

> The following table lists the attributes from a typical product export,
However the reference title is misleading, 
I was expecting to see a link to the full-list or see the **status** there as a common attribute.
This however, go through the **export** columns only.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
