### ISSUE TITLE
Add missing items to the Role Resources page 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1151]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/system/permissions-role-resources.html

## Description

Add missing items to the Role Resources page, not all items from the role resource administration page are displayed.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
closing issue as complete
