### ISSUE TITLE
Catalog | Describe gift card account history 

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1157]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/product-gift-card-accounts.html

## Description

Add a description of the "History" section for the Gift Card Account page

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
this appears to be completed.  https://docs.magento.com/user-guide/catalog/product-gift-card-accounts.html
