### ISSUE TITLE
Add a new topic about adding products to a category for the Category block

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1160]
# New topic request

## Description

Add a new topic about adding products to a category for the Category block.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Content checklist

- [x] The topic provides an explanation of how to add products into categories.
- [x] The topic provides steps for adding products into categories.
- [x] The topic contains examples that shows how to add products into categories.

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
Again, there is no need to open an issue if you are already have the PR in progress.

**Comment by ZhovnirMaria** [comment]
Hi, @dobooth. Thank you, my mistake.

**Comment by hickskenh** [comment]
this appears to be completed.  https://docs.magento.com/user-guide/catalog/category-products-add.html
