### ISSUE TITLE
Describe Product Reviews moderation

### ISSUE THREAD

**Issue by ZhovnirMaria** [magento/merchdocs#1171]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/settings-advanced-product-reviews.html

## Description

Describe the moderation of product reviews by the Admin.

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable:

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
This appears to be completed.  https://docs.magento.com/user-guide/catalog/settings-advanced-product-reviews.html
