### ISSUE TITLE
Image missing from topic - Hotjar feedback

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#12]
# Bug report

## Description

Image link formatting error -- > image not displayed in topic.

Reported on Hotjar Incoming feedback #134

![image](https://user-images.githubusercontent.com/1128913/64628659-6b0cfd00-d3b7-11e9-8871-0d972afd18db.png)

https://docs.magento.com/m2/ce/user_guide/customers/customer-account-create-order.html

**Comment by shrielenee** [comment]
The image is rendering in the page. This issue is no longer relevant.
