### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by hugopessoa82** [magento/merchdocs#1203]
Hi, im the user Hugopessoa, (conart2018@gmail.com) im using magento from a Builderall app, i have my store working and everything is just fine, but as a Admin logged always from the Builderall site, i cant create a password, or it keeps me asking the password that i never created and the email for recovery password never arrived.

**Comment by erikmarr** [comment]
@hugopessoa82 thank you for your feedback. It sounds like you are using a third party app to build/launch Magento. We recommend you work with the Builderall site to resolve your error.
