### ISSUE TITLE
Update Gateway URL setting on page: /shipping/usps.html

### ISSUE THREAD

**Issue by Arafathi** [magento/merchdocs#1204]
Effective June 24th, 2021, USPS Web Tools will remove support for all unsecure HTTP endpoints. 
Gateway URL in Magento setting should change to https. 
The instruction on this page should get updated.

**Comment by ZhovnirMaria** [comment]
Hi, @Arafathi 
I have had a small investigation on your issue and found that in Magento version 2.4 the Gateway URL field didn’t change. It still has an unsecured HTTP endpoint. 
Could you please give me more details? 
Thank you 😊 
<img width="994" alt="Screenshot 2021-05-05 at 10 30 16" src="https://user-images.githubusercontent.com/79835574/117109645-a0850c00-ad8d-11eb-9ceb-cf8315495e3e.png">

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
Hi @dobooth, for this issue the following was done:

- created PR in the magento/magento2 repository to fix the link in Magento Admin - https://github.com/magento/magento2/pull/32947
- removed screenshot showing an incorrect link
- added hint about the upcoming release, as a temporary measure until a fix for Magento Admin is implemented

Please let me know if you have any suggestions.
Thank you!
