### ISSUE TITLE
Issue with catalog price rule in magento 2.4.2

### ISSUE THREAD

**Issue by leduydong94** [magento/merchdocs#1240]
In magento 2.4.2, when adding a catalog rule for a product with custom option, set from date before current date, the price of the option is reduced according to the rule, but when adding option, the price displayed on the product page is not reduced, however, when add to the cart the price is reduced. I think it's bug of magento 2.4.2
Video test in local magento 2.4.2CE: https://www.loom.com/share/16d5581e2feb4756b1388c157d5e48df
Feedback me if it's a bug. Thank you !

**Comment by leduydong94** [comment]
@magento I am working on this

**Comment by leduydong94** [comment]
@magento add to contributors team

**Comment by leduydong94** [comment]
Thank you

**Comment by dobooth** [comment]
Closing this as it is not a docs issue.
