### ISSUE TITLE
Add checkout page layout

### ISSUE THREAD

**Issue by Santoshziffity** [magento/merchdocs#1272]
# New topic request

## Description

Add New Checkout topic under the Path to Purchase

- https://docs.magento.com/user-guide/quick-tour/path-to-purchase.html

There is no description and design available for the checkout page under the Path to Purchase section.

There is no Quick Toor for the checkout page and we should show the checkout layout to customers.

![image](https://user-images.githubusercontent.com/77620932/117135610-d2659500-adc4-11eb-83e9-84f83745812e.png)

**Comment by Santoshziffity** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
@Santoshziffity Any action here?

**Comment by hickskenh** [comment]
Moved to Jira [COMDOX-224](https://jira.corp.adobe.com/browse/COMDOX-224)
