### ISSUE TITLE
Remove info about sending an email notification for Notify for Quantity Below in /catalog/inventory-backorders.html

### ISSUE THREAD

**Issue by poprasad** [magento/merchdocs#1275]
Notify for Quantity Below
The Notify for Quantity Below configuration option is configurable at the global, source, and product levels. **When it is enabled, the system sends an email notification when the product quantity reaches a level at or below the configured value.** For this example, a notification is triggered when the product has a quantity of 10 or less. When backorders are enabled, Notify for Quantity Below is determined by the Salable Quantity (Salable Quantity = Quantity - (Out-of-Stock Threshold))

But there is no email notification sent out per tickets below: 
https://jira.corp.magento.com/browse/MDVA-8099
https://jira.corp.magento.com/browse/MDVA-33783

**Comment by danidelcar** [comment]
@dobooth do you want me to take a look at this issue?, or need some help with it?

**Comment by danidelcar** [comment]
@leslietilling while grooming this issue, we saw this section was last updated in #955 . Do you know if this is still valid?

**Comment by dobooth** [comment]
Fixed.
