### ISSUE TITLE
Add custom input in offline payment method

### ISSUE THREAD

**Issue by Santoshziffity** [magento/merchdocs#1279]
# New topic request

## Description

Here I found many customizations on the checkout page.
But I have one suggestion to add one more topic to this.

**New Topic:** Add Custom Input Field in the offline payment method
- Means in the purchase order payment method we must add purchase order number. if  any customer wants to add more field with the purchase order number at that time these docs will help,

https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_overview.html

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
Thank you for your request @Santoshziffity . 
This issue ties to the DevDocs repository - https://github.com/magento/devdocs and will be reviewed and corrected there.
