### ISSUE TITLE
Clarify encryption key usage

### ISSUE THREAD

**Issue by Techbrunch** [magento/merchdocs#1304]
> Magento uses an encryption key to protect passwords and other sensitive data.

How is the encryption key used in relation to password ?

Source: https://docs.magento.com/user-guide/system/encryption-key.html

According to you documentation the password are hashed. Is the encryption key used as some kind of salt ?

> Currently Magento uses its own strategy for password hashing, based on different native PHP hashing algorithms. Magento supports multiple algorithms like MD5, SHA256, or Argon 2ID13. 

Source:  https://devdocs.magento.com/guides/v2.4/config-guide/secy/hashing.html

**Comment by dobooth** [comment]
Hi @Techbrunch Thanks for filing the issue. Couple things: If this is a devdocs issue, please file one in https://github.com/magento/devdocs/issues. Second, we are not super clear on what kind of info you are looking for. Are the docs incorrect?

**Comment by Techbrunch** [comment]
@dobooth I edited my issue so it's a bit clearer. According to your documentation "Magento uses an encryption key to protect passwords and other sensitive data" what passwords are we talking about here since users password are supposed to be hashed and not encrypted.

**Comment by hickskenh** [comment]
Moved to Jira [COMDOX-223](https://jira.corp.adobe.com/browse/COMDOX-223)

**Comment by hickskenh** [comment]
closing
