### ISSUE TITLE
Feedback on page: /stores/admin-session-lifetime.html

### ISSUE THREAD

**Issue by FusionsoftUK** [magento/merchdocs#1305]
This still does not work, regardless of the settings in Magento, users are thrown out after 15 minutes.

This has been an issues since the beginning of time.

I have checked session.gc_maxlifetime'  and session.cookie_lifetime and these are both fine.

Bill.

**Comment by dobooth** [comment]
Hi @FusionsoftUK Thanks for the issue. We suspect this is more of a support issue: https://support.magento.com/hc/en-us.
If there needs to be a doc update, please provide more details.
