### ISSUE TITLE
ReCaptcha missing from Admin

### ISSUE THREAD

**Issue by mohmyster** [magento/merchdocs#1323]
Hi,

My hosting provider has updated my magento and when logging into admin I cant see the option for security in the back end.

Is this something that I can fix easily, any advice please?

Magento previous version 2.3.6-p1 to 2.3.7.

Thanks

Affected page: /configuration/security/google-recaptcha.html

**Comment by mohmyster** [comment]
I cant see an option here for security (see attached).

I am on magento 2.3.7
Shared windows hosting Apache 2.4.46
PHP 7.2.34
My SQL 5.7.34
Linux
![missing button securty](https://user-images.githubusercontent.com/83918537/119991030-ee71e600-bfc0-11eb-946f-1b789c34fb88.png)

**Comment by danidelcar** [comment]
checking into this issue

**Comment by bdenham** [comment]
@danidelcar you got an update for this?

**Comment by danidelcar** [comment]
> @danidelcar you got an update for this?

Looking into it @bdenham , thanks!

**Comment by hickskenh** [comment]
@danidelcar Hey Danny.  have you guys determined if this is a docs issue or something to do with an upgrade?  Also, this is for 2.3.7 which is KTLO. Should it be addressed?

**Comment by hickskenh** [comment]
@danidelcar checking on this again.

**Comment by danidelcar** [comment]
@mohmyster could you confirm that "security" appears now outside the general tab, as a completely separate tab?. I do not see it as a docs issue @hickskenh unless our docs show the wrong config or screen. I see our docs with the latest info here: https://docs.magento.com/user-guide/stores/security-google-recaptcha.html

**Comment by dobooth** [comment]
Closing as outdated. @mohmyster please reopen if there is still an issue with the docs.
