### ISSUE TITLE
Confirm you can use decimal for items in a shopping cart

### ISSUE THREAD

**Issue by voodoorabbit** [magento/merchdocs#1340]
https://docs.magento.com/user-guide/catalog/inventory-configure-inventory-management.html

Products can be set up in Magento 2 to be sold in decimal quantities. 

Why has the qty field on the shopping cart page been cast to an int instead of a float?
![ShoppingCart](https://user-images.githubusercontent.com/85914369/121983465-b6e2a680-cdd4-11eb-8004-f4699b30f408.jpg)

Same in the backend, when you are creating manual order, the qty field has been cast to an int instead of a float.
![Backend-Order-Creation](https://user-images.githubusercontent.com/85914369/121983470-b9450080-cdd4-11eb-9f7c-1cc088b7e0c3.jpg)

**Comment by dobooth** [comment]
Did you see the config option: 
'Qty Uses Decimals | Allows decimal amounts, instead of whole numbers, for the quantity of a product. This is helpful for products sold by weight, volume, or length. Specified on the level of Source, calculated on the Stock level based on assigned Sources.'?

**Comment by voodoorabbit** [comment]
yes I know that. I have set the products to decimal qty. You can add a decimal qty to the shopping cart. If you try to adjust the decimal qty on the shopping cart, from say 0.5 to 0.75 you get an error.

**Comment by voodoorabbit** [comment]
never-mind we found the issue, it was with the Porto Theme.
It looks like the Porto theme's cart template in:

app/design/frontend/Smartwave/porto/Magento_Checkout/templates/cart/item/default.phtml

is out of sync with the core Magento template. It looks like Magento fixed the issue in 2019 in this [change](https://github.com/magento/magento2/commit/06a1aa1b1b5830ccc17c2ebb2fdc713892d22d59).
