### ISSUE TITLE
The relationship between products and categories 

### ISSUE THREAD

**Issue by khrystynastolbova** [magento/merchdocs#1342]
# Bug report

## Description

<img width="1114" alt="Screenshot 2021-06-15 at 14 00 21" src="https://user-images.githubusercontent.com/79088059/122041870-1d21f600-cde2-11eb-91c0-58d6c09e3da4.png">

https://docs.magento.com/user-guide/catalog/categories.html

To create a product, the required fields are name, sku and price. The category assignment is not required.
Products may be assigned to zero or more categories.

### Steps to reproduce

1. Add a new product
2. Leave the 'Categories' field empty
3. Save
4. Received the message 'You saved the product.'
<img width="1444" alt="Screenshot 2021-06-15 at 14 09 48" src="https://user-images.githubusercontent.com/79088059/122043328-e5b44900-cde3-11eb-82e4-3479d0f4850b.png">

## Possible solutions

Change text to something like "Products may be assigned to zero or more categories."

## Magento release version

- 2.4.2
- 2.3.6-p1

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
