### ISSUE TITLE
Update Admin table in Role Resources topic

### ISSUE THREAD

**Issue by hickskenh** [magento/merchdocs#135]
# Topic clarification/correction request

The Admin table needs to be updated to reflect options in each of the admin panel sections.

## Topic Link

user_guide/system/permissions-role-resources.html

## Description

The Admin table needs to be updated to reflect options in each of the the admin panel sections. The current table doesn't include all available options. Need to review at ce, ee, and b2b levels and version options accordingly.

**Comment by danidelcar** [comment]
@leslietilling @hickskenh can this issue be groomed so can be open to community for work?

**Comment by leslietilling** [comment]
I think some changes have happened there since this was originally opened. If we want to open this up to Community, we should provide more details of the specific items missing that should be added, and any that are ee or b2b only.

**Comment by dobooth** [comment]
Closing this as out of date. I don't see an "Admin" table.
