### ISSUE TITLE
Video for Page Builder docs not working.

### ISSUE THREAD

**Issue by deltaworld** [magento/merchdocs#1365]
# Bug report
Video for Page Builder hosted on YouTube is set to unlisted and is now inaccessible and private
## Description
When attempting to access the video on the Page Builder page https://business.adobe.com/products/magento/ecommerce-cms.html the link takes you to https://business.adobe.com/products/magento/ecommerce-cms.html#featured-video. The video the link points to is hosted on YouTube and as the video was unlisted, since the 23 July, all unlisted videos are now set to Private and the video is not publicly accessible.

_What is the issue/current behavior?_
Clicking on the link for the video https://business.adobe.com/products/magento/ecommerce-cms.html#featured-video produces a message from YouTube "Private video | Sign in if you've been granted access to this video"

### Steps to reproduce

_(OPTIONAL) What needs to be done to replicate this issue? Provide Gist if needed._

1. Visit https://business.adobe.com/products/magento/ecommerce-cms.html
2. Click on the video link https://business.adobe.com/products/magento/ecommerce-cms.html#featured-video

## Expected result
Video plays as expected 

_When this issue is resolved, what is the expected result/behavior?_
The video is publicly accessible for public viewing.

## Possible solutions
re-upload video as public and not as unlisted

## Additional information
https://9to5google.com/2021/06/23/youtube-unlisted-videos/

**Comment by dobooth** [comment]
Closing as not a docs issue. Correct team has been notified.
