### ISSUE TITLE
Feedback on page: /marketing/email-template-list.html

### ISSUE THREAD

**Issue by steph-od** [magento/merchdocs#1380]
The 'Credit Limit Updated' template name is missing and breaking the table formatting. See the image attached.

<img width="687" alt="Email Template List | Adobe Commerce 2 4 User Guide 2021-07-09 14-11-52" src="https://user-images.githubusercontent.com/87159466/125013295-b1b90480-e0bf-11eb-8b4b-81ea82f47b74.png">

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
