### ISSUE TITLE
No more "Add Block Names to Hints". User docs should be updated

### ISSUE THREAD

**Issue by engcom-November** [magento/merchdocs#1381]
# Topic clarification/correction request
Remove "Add Block Names to Hints" and add "Add Block Class Type to hints" where ever required in the docs.

## Topic Link
https://docs.magento.com/user-guide/configuration/advanced/developer.html 
https://docs.magento.com/user-guide/system/template-path-hints.html 

## Description
Admin -> Stores -> Configuration -> Advanced -> Developer -> Debug section -> "Add Block Names to Hints" option was removed from here long back but the docs are outdated and have to be updated accordingly.

## Magento release version
2.4
## Possible solutions
Remove "Add Block Names to Hints" and add "Add Block Class Type to hints" where ever required in the docs.

## Additional information
Please find the below GitHub commit to check further details about the changes made related to this feature.
https://github.com/magento/magento2/commit/7238228429b1
![image](https://user-images.githubusercontent.com/60198231/125304875-906c4880-e34b-11eb-8c19-73c9b35aea18.png)

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
