### ISSUE TITLE
Document the Robots Directive Exception Rules

### ISSUE THREAD

**Issue by Crissov** [magento/merchdocs#1389]
/marketing/search-engine-robots.html

The configuration of _Robots Directive Exception Rules_ is not documented in the [User Guide](https://docs.magento.com/user-guide/marketing/search-engine-robots.html) yet. It's unclear, for instance, what exactly the regular expressions match against.

![image](https://user-images.githubusercontent.com/6200185/125762667-53016f20-3ab0-4644-b3b9-bef0b152fddc.png)

**Comment by hickskenh** [comment]
moved to Jira [COMDOX-222](https://jira.corp.adobe.com/browse/COMDOX-222)

**Comment by hickskenh** [comment]
closing
