### ISSUE TITLE
Wish List Configuration - Specify multiple wishlist is not in open source version

### ISSUE THREAD

**Issue by df2k2** [magento/merchdocs#1407]
# Topic clarification/correction request

Wish List configuration page in the docs shows an option for multiple wish list settings but does not specify that it is commerce version only.  Open source does not have this feature and it should be noted.

## Topic Link

https://docs.magento.com/user-guide/marketing/wishlist-configuration.html

## Description

There is no indication on this page that the multiple wishlists feature is Adobe commerce only.

![image](https://user-images.githubusercontent.com/4868368/126736619-652e923c-1a77-4a09-9891-f77e72806533.png)

## Magento release version

- 2.4

## Possible solutions

![image](https://user-images.githubusercontent.com/4868368/126736901-546a75fa-274c-4d30-bab7-1cff82afc59d.png)

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
