### ISSUE TITLE
Expand the Catalog media URL format topic description

### ISSUE THREAD

**Issue by EvheniiaKolkhiieva** [magento/merchdocs#1421]
# Topic clarification/correction request

## Topic Link
https://docs.magento.com/user-guide/configuration/general/web.html#url-options

_A link to the topic that needs clarification or correction._

## Description
This issue is related to the discussion in https://github.com/magento/merchdocs/pull/1230 and https://github.com/magento/merchdocs/issues/1111

Re:

> However, I think that it is still unclear with the current proposition, maybe you could:
> 
> provide an example for both options
> provide more explanation of why one would pick one option over the other as to explain what the benefit would be of one option versus the other

_What needs to be clarified or corrected in this topic?_

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

- no

## Possible solutions

_(OPTIONAL) What would a solution for this issue look like?_

## Additional information

_(OPTIONAL) What other information can you provide about this issue?_

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
@EvheniiaKolkhiieva please advise if you are working on this or should be removed?

**Comment by leslietilling** [comment]
The referenced link is part of the Configuration Reference, so we do not provide examples on that page. More information would be needed to update the topic on Experience League: https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/catalog-urls.html?lang=en#configure-catalog-urls

**Comment by hostep** [comment]
Great! 😞😞😞

**Comment by leslietilling** [comment]
@hostep  If we have some information to work with, we can improve the information on https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/catalog-urls.html#configure-catalog-urls

There is an icon to log an issue for the public repository. Sorry for the inconvenience, but we are no longer publishing from this one.
