### ISSUE TITLE
Determine if you can have a different price at the store level

### ISSUE THREAD

**Issue by sparrowek** [magento/merchdocs#1424]
Is this correct? Can I have a different price at the store level?

Look here
https://magento.stackexchange.com/questions/210203/different-prices-for-different-store-views

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
@ZhovnirMaria please advise if you still are working on this ticket or should it be assigned to someone else?

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/catalog/products/pricing/catalog-price-scope.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
