### ISSUE TITLE
Bullets and icons offset

### ISSUE THREAD

**Issue by hguthrie** [magento/merchdocs#1434]
Using two separate browsers, the icons look offset.

-  Safari on the left, icons appear dropped
-  Chrome on the right, icons appear as expected

<img width="600" alt="Screen Shot 2021-08-11 at 16 01 24" src="https://user-images.githubusercontent.com/5817319/129103076-b618d18d-772d-4090-b810-4e3284feb221.png">

**Comment by hguthrie** [comment]
@belbiy @bdenham Do you also see this? Is this something either of you can help with?

**Comment by belbiy** [comment]
Yep, i see it. It's relatively easy to fix, by adding a `top: 0` property: 
![Screen Shot 2021-08-16 at 12 20 59 PM](https://user-images.githubusercontent.com/752610/129603933-a3016ed9-4f1b-4d96-a4c8-7cc5f415066a.png)

**Comment by bdenham** [comment]
Yep, on it.

**Comment by dshevtsov** [comment]
@hguthrie please add a link to the page that's on screenshot for future testing and validation.

**Comment by hguthrie** [comment]
No longer seeing the problem on the [About page](https://docs.magento.com/user-guide/magento/about-this-release.html), so it must have been corrected. Closing
