### ISSUE TITLE
Merge JS and Bundling setting confusion

### ISSUE THREAD

**Issue by onlinebizsoft** [magento/merchdocs#1462]
# Bug report

https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html
"To configure JavaScript bundling, you must disable Javascript file merging. Bundling will not work as the merging of files excludes bundling"

https://devdocs.magento.com/guides/v2.4/performance-best-practices/advanced-js-bundling.html
"Enabling merging without also enabling bundling is not useful because Magento uses RequireJS. If you don’t enable bundling, Magento only merges RequireJS and its configuration. When you enable both bundling and merging, Magento creates a single JavaScript file"

## Description

The first desceiption is misleading that if we enable merge then bundling is skipped while the second description confirms the difference when we enable both merge and bundling.

_What is the issue/current behavior?_

### Steps to reproduce

_(OPTIONAL) What needs to be done to replicate this issue? Provide Gist if needed._

1. First Step
1. Second Step
1. Etc.

## Expected result

_When this issue is resolved, what is the expected result/behavior?_

## Possible solutions

_(OPTIONAL) What would a solution for this issue look like?_

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

## Additional information

_(OPTIONAL) What other information can you provide about this issue?_

**Comment by dobooth** [comment]
Hi @onlinebizsoft We agree that there is a contradiction there, but could you please open this in the devdocs repo?

**Comment by onlinebizsoft** [comment]
I opened https://github.com/magento/devdocs/issues/9133
