### ISSUE TITLE
Feedback on page: /marketing/google-enhanced-ecommerce.html

### ISSUE THREAD

**Issue by costakkk** [magento/merchdocs#1467]
The events in the user guide are written Uppercase i.e. "AddToCart" while they actually lowercase "addToCart". Please correct user guide:

AddToCart -> addToCart 
Checkout -> checkout   .... this is missing completely under "3. Complete the individual tracking configurations."
CheckoutOption -> checkoutOption
ProductClick -> productClick
PromotionClick -> promotionClick
RemoveFromCart -> removeFromCart

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
