### ISSUE TITLE
Feedback on page: /system/data-attributes-product.html

### ISSUE THREAD

**Issue by Sv0gls** [magento/merchdocs#148]
The documentation for **related_skus**, **crosssell_skus**, **upsell_skus** does not mention how to set the position (sort order) for each of the comma seperated SKUs via a CSV import.

Expected behavior would be that Magento sets the position according to the order of the comma separated SKUs (from left to right). 

However, Magento appears to set the default order to the product ID (row ID) in ascending order. The product with the lowest ID is set as the first product and the product with the highest ID is set as the last product.

**Comment by ccondra** [comment]
This would be a good new topic called "Product Relationships" under [Data Transfer Examples](https://docs.magento.com/m2/ee/user_guide/system/data-transfer-examples.html).   See [Importing Bundle Products](https://docs.magento.com/m2/ee/user_guide/system/data-transfer-bundle-products.html) for some ideas as to how you might approach the subject.

Then, link to the new topic from [Product Relationships](https://docs.magento.com/m2/ee/user_guide/marketing/product-relationships.html) and  [Related Products, Up-Sells, and Cross-Sells](https://docs.magento.com/m2/ee/user_guide/catalog/related-products-up-sells-cross-sells.html).

**Comment by Sv0gls** [comment]
I created a pull request to update the page with information about how to set the position of the SKUs of the related_skus, crosssell_skus and upsell_skus attributes. As a merchant, I would expect to find this information on this page and in the sample file (CSV) that is provided in the System > Data Transfer > Import > Products section in Magento 2.

#160

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by hguthrie** [comment]
Closing because the referenced PR was merged.
