### ISSUE TITLE
Add info about multiple quantities in Hidden Tax topic

### ISSUE THREAD

**Issue by nfplee** [magento/merchdocs#1492]
How does this work with multiple quantities? Is it a case of multiplying the hidden tax by the quantity? I'm guessing not as the "Tax Calculation Method Based On" setting will surely effect this.

Could you add some information on this?

Topic: https://docs.magento.com/user-guide/tax/hidden-tax-calculation.html

**Comment by hickskenh** [comment]
Moved to Jira
