### ISSUE TITLE
Add preconfigure step before enabling Approval Rules

### ISSUE THREAD

**Issue by katmoon** [magento/merchdocs#1540]
Feedback on page: [Approval rules](https://docs.magento.com/user-guide/customers/account-dashboard-approval-rules.html)

Please add that the "purchaseorder.validation" needs to be setup in order for Approval Rules to work correctly

**Comment by hickskenh** [comment]
Moved to Jira [COMDOX-218](https://jira.corp.adobe.com/browse/COMDOX-218)

**Comment by dshevtsov** [comment]
Moving an issue to Jira doesn't make it resolved. Also, posting internal links is not allowed in public repos.
