### ISSUE TITLE
Issue on page: /shipping/fedex.html

### ISSUE THREAD

**Issue by sanjaygswmi** [magento/merchdocs#1560]
I am getting an error on checkout page "Sorry, no quotes are available for this order at this time". After debugging I found this error log in shipping.log

main.CRITICAL: Could not connect to host {"exception":"[object] (SoapFault(code: 0): Could not connect to host at <magento_root>/vendor/magento/module-fedex/Model/Carrier.php:520)"} []

What should I do?

**Comment by dobooth** [comment]
HI @sanjaygswmi Sorry to hear of the trouble. Unless this is an error in the documentation, I suggest you contact Support: https://support.magento.com/hc/en-us or ask on a forum such as StackExchange: https://magento.stackexchange.com/ If it is a docs issue, please provide more details.
