### ISSUE TITLE
Feedback on page: /cms/content-staging-scheduled-update.html

### ISSUE THREAD

**Issue by surendragamage** [magento/merchdocs#1598]
Hi Team,
The following statement available in [ https://docs.magento.com/user-guide/cms/content-staging-scheduled-update.html ] document is quite confusing.

`An end date cannot later be added to a price rule campaign that was originally created without an end date. In such a case it is necessary to create a duplicate campaign that includes the end date that is needed`

This needs to be correct something similar to below.

`In such a case it is necessary to create a new campaign that includes the start date which you think that the previous schedule should end and keep the end date empty. Then the new schedule will be active and continue with the actions defined in it.`

According to the current recommendation available in the document,
if we create a new/duplicate schedule with an end date, it will end on the given date and the previous campaign without an end date will active again. So that is not the correct solution for the price rule campaign that was originally created without an end date.

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
Thank you for the great notice @surendragamage !

**Comment by ccondra** [comment]
This has enough information to move to development. Thank you!

**Comment by hickskenh** [comment]
Addressed in PR #461
https://github.com/magento-commerce/merchdocs/pull/461
