### ISSUE TITLE
Hi @KristiChadderdon. Thank you for your report.

### ISSUE THREAD

**Issue by KristiChadderdon** [magento/merchdocs#1616]
Hi @KristiChadderdon. Thank you for your report. 
To speed up processing of this issue, make sure that you provided sufficient information. 

Add a comment to [assign the issue](https://devdocs.magento.com/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this` 

---
-  Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

_Originally posted by @m2-assistant[bot] in https://github.com/magento/merchdocs/issues/1613#issuecomment-963505695_

**Comment by KristiChadderdon** [comment]
Please assist with my issues.

**Comment by dobooth** [comment]
Closing for lack of content.
