### ISSUE TITLE
Add Excluded Websites to customer group topic

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1617]
Is it possible to add a note that the ``Exclude Website(s)`` feature was added in 2.4.3?

https://docs.magento.com/user-guide/customers/customer-groups.html#create-a-customer-group

```
5.  Select the Excluded Website(s) that you want to exclude from the group.
```

https://devdocs.magento.com/guides/v2.4/release-notes/commerce-2-4-3.html#performance-enhancements

```
Performance enhancements
This release includes enhancements that decrease indexation time for Product Price and Catalog Rule indexers. 
Merchants can now exclude a website from a customer group or shared catalog, which reduces the number of records for indexing and improves indexing times.
```

**Comment by hickskenh** [comment]
As a general rule, we maintain documentation for current release versions.  It is not feasible for us to add notes each time options are added.
