### ISSUE TITLE
Need to clarify priority rules

### ISSUE THREAD

**Issue by Crissov** [magento/merchdocs#1643]
https://docs.magento.com/user-guide/marketing/price-rules-cart-create.html

The info box in step 1.5 says:

> The Priority setting is important when two cart rules/coupon codes are valid for the same product at the same time.
> The rule with the highest Priority setting (1 being the highest) will control the cart action.

_Priority_ can be set to `0` as well. It appears undocumented what this means effectively: 

- Is it higher than the allegedly highest priority `1`?
- Is it a default priuority that is lower than all explicit priorities?

Furthermore, what happens if two rules contradict each other but have the same priority?

Also see https://github.com/magento/magento2/issues/27202#issuecomment-627331528

**Comment by hickskenh** [comment]
moved to [COMDOX-214](https://jira.corp.adobe.com/browse/COMDOX-214)
