### ISSUE TITLE
Incorrect cron guidance between Cloud and on-prem

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1651]
Topic: [/system/cron.html](https://docs.magento.com/user-guide/system/cron.html)

```
Make sure that the base URLs for the store are set correctly, so the URLs that are generated during cron operations are correct. See Set up cron jobs in the Commerce Developer Guide.
```

The **See [Set up cron jobs](https://devdocs.magento.com/cloud/configure/setup-cron-jobs.html) in the Commerce Developer Guide** link is specifically applicable to Adobe Commerce Cloud only and do not apply to On-Premise

This is more generic and applies to On-Premise: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html

**Comment by ccondra** [comment]
This is ready for dev - please add a note for on-prem installations with a link to the referenced devdocs topic.

**Comment by hickskenh** [comment]
addressed in [PR 462](https://github.com/magento-commerce/merchdocs/pull/462)
