### ISSUE TITLE
Wrong assignment of sales channel to stock

### ISSUE THREAD

**Issue by HenKun** [magento/merchdocs#1687]
https://github.com/magento/merchdocs/blob/4267dc13469a89de741c44eb3cc31b471d9a1416/src/catalog/inventory-about-sources-stocks.md?plain=1#L27

The image suggests one sales channel can be assigned to multiple stocks. "Amazon Marketplace" Sales channel is assigned to stocks "UK Store" and "US Store". This is wrong. Amazon Marketplace can only be assigned to one of the stocks, as correctly stated in the paragraph above the image.

Note: Same images is also used on https://docs.magento.com/user-guide/catalog/inventory-stock.html

**Comment by hickskenh** [comment]
Addressed in PR 458

**Comment by HenKun** [comment]
I don't see the change, in neither of the pages. The PR isn't even linked or available

**Comment by hickskenh** [comment]
the pr was approved last night, but wasn't merged til this morning.  https://github.com/magento-commerce/merchdocs/pull/458
