### ISSUE TITLE
Incomplete instructions for installing Live Search

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1697]
# Bug report

## Description

The article doesn't list any dependencies for installing Live Search

### Steps to reproduce

N/A

## Expected result

It should guide the merchant to install the dependencies

## Possible solutions

Taking the text from the Product Recommendations:

```
The magento/product-recommendations module requires the following dependencies:

Please install the following dependencies:

* data-services — This module enables behavioral data collection by tracking [user events on the page](https://devdocs.magento.com/recommendations/events.html). This type of data is required by Adobe Sensei to compute product affinities based on production shopper behavior like product views, products added to a cart, and checkouts. Adobe Sensei then uses this information to create and train machine learning models for each website and store view. This unlocks recommendation types like “Customers who viewed this, also viewed…”, which automatically adjusts with shopper behavior over time. Magento and Adobe Sensei do not collect personally identifiable information.
* saas-export — This module syncs catalog data. This type of data provides product information to the Product Recommendations service so it can accurately return product names, pricing, images, URLs, inventory and availability, and other attributes.
```

TODO: 
- Replace ``magento/product-recommendations`` with ``magento/live-search``
- Adjust the definition of each module listed above according to how it works with Live Search

## Magento release version

All versions

## Additional information

**Comment by danidelcar** [comment]
Hi @ccondra could you take a look please?. As well, @ak77-prime are you referring to this page?: https://docs.magento.com/user-guide/live-search/install.html

**Comment by ak77-prime** [comment]
Yes, I had a customer who was trying to install Live Search but composer didn't install the required dependencies so he couldn't configure the Sensei Services Connector

**Comment by ccondra** [comment]
These are actually listed at the bottom of the topic, but should be moved up to the beginning. Thanks!
