### ISSUE TITLE
issue in magento gift Registry 

### ISSUE THREAD

**Issue by komal8008** [magento/merchdocs#1698]
when I am creating a new birthday gift registry in the Magento enterprise 2.4.3 store it shows me duplicate entry fields for first name, last name, and email. as shown below:
![image](https://user-images.githubusercontent.com/78193642/153413269-3ffddbf3-c93c-47f1-861b-a268a754ad46.png)

**Comment by komal8008** [comment]
@magento-devops-community-builds-svc 
@magento 
i am working on this

**Comment by dobooth** [comment]
Hi @komal8008 This does not appear to be an issue with documentation. If you are continuing to have issue with the gift registry, we suggest you contact support to assist with a resolution. https://support.magento.com/hc/en-us
