### ISSUE TITLE
Remove links from headings in topics

### ISSUE THREAD

**Issue by shrielenee** [magento/merchdocs#17]
# Bug report

Remove links from headings in topics. This is not a DevDocs style and I suggest removing links from headings to further match with DevDocs formatting and styles

## Description

Page that is affected (many more in addition to this):

- https://docs.magento.com/m2/ce/user_guide/reports/sales-reports.html
- https://docs.magento.com/m2/ce/user_guide/reports/bi-essentials-report-builder.html

## Expected result

Headings do not contain hyperlinks

## Possible solutions

Remove hyperlinks from headings

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/merchdocs/pull/32

**Comment by shrielenee** [comment]
Fixed by #32
