### ISSUE TITLE
Number of data spaces available

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1702]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/configuration/services/saas.html#saas-identifier

## Description

This point in bold needs clarification:

The number of SaaS Data Spaces that appears depends on your Commerce license:
**Adobe Commerce - One production data space; two testing data spaces;**
Magento Open Source - One production data space; no testing data spaces

Only the license holder will be able to generate multiple data spaces - and the account needs to be current.

## Possible solutions

```
Adobe Commerce - One production data space; two testing data spaces. As long as the API keys were generated on the account associated with the Adobe Commerce license and the account is current.
```

_(OPTIONAL) What would a solution for this issue look like?_

## Additional information

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
