### ISSUE TITLE
Spying on Grammarly

### ISSUE THREAD

**Issue by jchassery12** [magento/merchdocs#1704]
# New topic request

## Description

_What topic is missing from documentation?_

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

- ...

## Content checklist

_List specific information or details to include in this topic._

_Use the following checklist template as a starting point:_

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains examples that shows ____.
- [ ] The tutorial should walk-through a complicated process.
- [ ] Other (please specify)

## Additional information/resources

_(OPTIONAL) Any information you already know or other online resources that cover this topic._

**Comment by bdenham** [comment]
nothing here to act on.
