### ISSUE TITLE
Issue with Product Varient Price

### ISSUE THREAD

**Issue by avinashstpl** [magento/merchdocs#1713]
We have created multiple option of 1 product and when we are adding price of each variant then its showing price like
+120
-20

Our base product is Rs 250 for 12 ml then other are 10 ml Rs.230 and 20ml Rs 250.

Kindly help us to fix the issues

![image](https://user-images.githubusercontent.com/35250045/156763678-c5d559dd-11ac-4680-b7f6-3d5e2bce9cf9.png)

**Comment by dobooth** [comment]
Hi @avinashstpl Thanks for writing. This is more of a support issue rather than a docs issue. Please check with Support at https://support.magento.com/hc/en-us for help with your issue.

**Comment by ccondra** [comment]
Rather than setting is up as a simple product with configurable options, it might be better to create a configurable product with multiple (simple) product variations.  That way, the price won't be shown as a markup in relation to the base product price.  I hope this helps!
