### ISSUE TITLE
How to use the Scheduled Update to schedule Promotions

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1715]
# New topic request

## Description

I have a customer who is confused about how to activate a Cart Price Rule and asked that we clarify this in the User Guide.

```
So you're saying that if a rule is created and we want it active for a specified time period then do the following:
1. Set the rule to be set "inactive" by default
2. Schedule new update with specified time period and in the schedule set the rule to be active
As such, with the above, the price will revert back to original when the scheduled time is over.

If that's the case, then please add examples in the Magento user guide https://docs.magento.com/user-guide/marketing/price-rules-cart.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=price%20cart%20rule to explain this as it is not clear that the steps above would be required.
```

## Magento release version

All versions

## Content checklist

_List specific information or details to include in this topic._

How to create a Catalog Price Rule that would only apply during a specific time period
How to update a Catalog Price Rule that would modify the discount amount during a specific time period:

_Use the following checklist template as a starting point:_

- [X] The topic provides an explanation of how _Scheduled Updates for promotiosn_ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains examples that shows ____.
- [X] The tutorial should walk-through a complicated process.
- [ ] Other (please specify)

## Additional information/resources

To create a Catalog Price Rule that would only apply during a specific time period:
1. When you first configure the Catalog Price Rule, set the status = Disabled/Inactive
2. Create a new Scheduled Update 
3. In the popup window, specify the Start and/or End time of the promo
4. Change the status of the rule to be Enabled/Active

To update a Catalog Price Rule that would modify the discount amount during a specific time period:
1. Create a new Scheduled Update 
2. In the popup window, specify the Start and/or End time of the promo
3. Under the Actions section, change the Discount Amount accordingly

**Comment by hickskenh** [comment]
Moved to Jira - [COMDOX-216](https://jira.corp.adobe.com/browse/COMDOX-216)
