### ISSUE TITLE
Sentence correction

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1722]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/inventory-about-ssa.html#source-selection-algorithm

## Description

Needs correction:

```
SSA is able extensible for third party support and custom algorithms for recommending cost effective shipments.
```

## Magento release version

N/A

## Possible solutions

```
SSA is extensible for third-party support and custom algorithms for recommending cost-effective shipments.
```

## Additional information

**Comment by hickskenh** [comment]
Addressed in PR 457
https://github.com/magento-commerce/merchdocs/pull/457
