### ISSUE TITLE
"Send" is listed twice

### ISSUE THREAD

**Issue by alangwilson** [magento/merchdocs#1723]
# Bug report

## Description
Send is shown twice in the list at the top of the page

### Steps to reproduce
https://docs.magento.com/user-guide/stores/b2b-configure-quotes.html

## Expected result
List it once.

## Possible solutions
Remove the second/duplicate instance

**Comment by hickskenh** [comment]
Addressed with PR#460  https://github.com/magento-commerce/merchdocs/pull/460

**Comment by hickskenh** [comment]
closing issue after merge
