### ISSUE TITLE
Invitations, as described in the documentation, are not in the admin

### ISSUE THREAD

**Issue by rob-gonz** [magento/merchdocs#1735]
# Topic clarification/correction request

## Topic Link

_A link to the topic that needs clarification or correction._

## Description

_What needs to be clarified or corrected in this topic?_

## Magento release version

2.4.3-p1

- ...

## Possible solutions

Updating the documentation to reflect the removal or new location of the feature. Or fixing the code so the feature is accessible. I do not know what the intended state is.

## Additional information

This documentation: https://docs.magento.com/user-guide/customers/account-dashboard-my-invitations.html is inconsistent with the admin menu experience.

**Comment by dobooth** [comment]
Hi @rob-gonz Thanks for writing. The Invitations feature is for Adobe Commerce only. Are you looking at Commerce or the Magento Open Source version?

**Comment by dobooth** [comment]
@rob-gonz Thanks for the reply.  I am not seeing the issue in my instance. Can you be more specific as to the error or perhaps provide a screenshot of what you are seeing?

**Comment by leslietilling** [comment]
@rob-gonz  This content has been migrated to the Adobe Experience League: https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/events/invitations.html#my-invitations

Hopefully it clarifies the issue. Invitations are enabled in the Admin, and then available to customers in their account on the storefront. Let us know if you need additional information about this feature.

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/marketing/promotions/events/invitations#my-invitations.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
