### ISSUE TITLE
Images of the simple product creation do not take into account the MSI functionality

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#1739]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/catalog/product-create-configurable.html#step-3-configure-the-images-price-and-quantity

## Description

The images shown under **Method 2** of ``Use one of the following methods to configure the quantity:`` do not match the current functionality when Multi-Source Inventory is enabled.

_What needs to be clarified or corrected in this topic?_

The images should be updated to match the MSI functionality

## Magento release version 

2.3
2.4

## Possible solutions

Update the images to reflect the MSI functionality - perhaps add a different image for the MSI instance and caption/annotate it as necessary

## Additional information

See https://magento.zendesk.com/agent/tickets/529392

**Comment by dobooth** [comment]
@ak77-prime Thanks for the issue. I have looked in my instance and I don't see the image mismatch. Can you attach a screenshot of what it should look like?

**Comment by ak77-prime** [comment]
![1739-msi-stock](https://user-images.githubusercontent.com/68703716/179338564-448b905f-f3b2-4740-a1b3-0eb9a4dd33c9.png)

**Comment by leslietilling** [comment]
We are no longer updating content in this repository and will have to migrate this issue to https://git.corp.adobe.com/AdobeDocs/commerce-admin.en/issues

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/catalog/products/types/product-create-configurable.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
