### ISSUE TITLE
Misses information on how to set the cookie lifetime to infinite.

### ISSUE THREAD

**Issue by Eddcapone** [magento/merchdocs#1742]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/customers/customer-online-options.html

## Description

Misses information on how to set the cookie lifetime to infinite.

## Magento release version

2.4.2

**Comment by dobooth** [comment]
Hi @Eddcapone Thanks for writing. We don't recommend setting cookies that don't expire, so we are disinclined to add it to the docs.

**Comment by Eddcapone** [comment]
Hi @dobooth, you could add a note where you explain why you don't recommend it. On many sites there is a feature where to user can opt-in via checkbox on the login form, to stay signed in forever, so it makes sense.
