### ISSUE TITLE
GTM_M2_Config_json.txt no longer

### ISSUE THREAD

**Issue by seb-jean** [magento/merchdocs#1749]
Hello,

On the https://docs.magento.com/user-guide/marketing/google-tag-manager.html page, the [GTM_M2_Config_json.txt](https://docs.magento.com/m2/downloads/GTM_M2_Config_json.txt) file is no longer the correct one since the arrival of Google Analytics 4 (GA4).

The tags are still "Google Analytics: Universal Analytics".
They should be "Google Analytics: GA4 Event".

Thanks :)

**Comment by dobooth** [comment]
@leslietilling This seems like a file we shouldn't be maintaining on merchdocs. Concur?

**Comment by shrielenee** [comment]
Yes. I am currently trying to get info from the vendor workers who worked on Google Tag Manager to see what we can do about the file. Talking with Mahesh Singh.

**Comment by shrielenee** [comment]
Ok. I found out the best path to updating this topic is to use this: https://www.optimizesmart.com/importing-exporting-container-tag-in-google-tag-manager/

The Step 1 section is not correct, as it mentions Google Analytics 3. The instructions in the topic above show you how to download and import the .txt file.

**Comment by superdav42** [comment]
Is there a correct file anywhere? I've been searching for updated docs on how to get GTM to work in magento > 2.4.5 and everything seems to be out-of-date.

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/marketing/google-tools/google-tag-manager.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
