### ISSUE TITLE
Currency Setup - Fixer.io changed there apis urls

### ISSUE THREAD

**Issue by amarroni** [magento/merchdocs#1753]
# Bug report

## Description
Trying to install a currency conversion using Fixer.io. I created a new account. Following the steps. When you go to fixer.io get free account.
Now apis are under APILayer instance of Fixer.io.

### Steps to reproduce

1. click on fixer.io link under documentation page. link go to https://fixer.io/
2. under fixer.io page you can click"set up free" redirecting to https://apilayer.com/marketplace/fixer-api#pricing
3. select a plan (free)
4. go to your dashboard account and get your api access key
5. Go to Adobe commerce admin panel and add this api access key
6. go to Currencies retas > Click using fixer.io converter rates

## Expected result
Add the rates expected configured

_When this issue is resolved, what is the expected result/behavior?_

## Possible solutions
Change from http://data.fixer.io/api/ to https://api.apilayer.com/fixer/
## Magento release version
2.4.4-p1

**Comment by dobooth** [comment]
Hi @amarroni. Thanks for the issue. I can't find the documentation page that you are referring to. Which topic is in error?

**Comment by amarroni** [comment]
@dobooth thank you for your replay. I'm referencing under this doc page https://docs.magento.com/user-guide/configuration/general/currency-setup.html
fixer.io moved to api.apilayer
 
<img width="1067" alt="currency-setup-issue" src="https://user-images.githubusercontent.com/5198527/187255890-67a647ef-59eb-4c73-a047-24b30339c123.png">

Best,
Alejandro.

**Comment by dobooth** [comment]
Thanks. That's what I thought but was looking for actual API links like your suggestion. I think the link to the homepage is probably ok as is. It is only the pricing page that goes to the other domain.

**Comment by dobooth** [comment]
Looked in to this. Links are ok as is.
