### ISSUE TITLE
Custom Variable documentation should be updated to reflect Page builder is available to Open Source

### ISSUE THREAD

**Issue by jasonfordAdobe** [magento/merchdocs#1758]
# Topic clarification/correction request

## Topic Link

[Adding Custom Variables](https://docs.magento.com/user-guide/marketing/variables-custom.html)

## Description

This topic is misleading, as it implies that Page Builder is exclusive to Adobe Commerce.

## Magento release version

N/A

## Possible solutions

Update to reflect current capabilities.

## Additional information

N/A

**Comment by leslietilling** [comment]
Fixed in migrated page on Experience League: https://experienceleague.adobe.com/docs/commerce-admin/systems/variables/variables-custom.html
