### ISSUE TITLE
Yotpo Setup

### ISSUE THREAD

**Issue by Tarn-dog** [magento/merchdocs#1760]
# Bug report

## Description

Yotpo config does not have a set-up guide - goes to 404 page not found 

### Steps to reproduce

1. stores
2. configuration
3. yotpo
4. yotpo_reviewsandvisualmarketing
2. setup
3. need help? setup guide

## Expected result

![Capture](https://user-images.githubusercontent.com/123370074/214023709-a33e33b5-eb5f-4946-9b46-c90bc000dcdd.PNG)

_When this issue is resolved, what is the expected result/behavior?_

Setup guide link to page

**Comment by leslietilling** [comment]
Will add a redirect for this old URL. Yotpo is no longer bundled with Commerce and all docs are available through the Marketplace or on the Yotpo site.
