### ISSUE TITLE
Encryption Key documentation says we use AES-256, but we ChaCha20-Poly1305 instead

### ISSUE THREAD

**Issue by JacobBrownAustin** [magento/merchdocs#1761]
# Topic clarification/correction request

## Topic Link

src/system/encryption-key.md

## Description

Documentation says that we " An industry-standard Advanced Encryption Standard (AES-256) algorithm is used to encrypt all data that requires decryption. "
This is no longer correct since Magento 2.3.0 as the default cipher is the IETF version of ChaCha20-Poly1305.

## Magento release version

_Which Magento release(s) are affected by the content changes: 2.4, 2.3? Specify a patch release number, if applicable._

2.3.x
2.4.x

## Possible solutions

_(OPTIONAL) What would a solution for this issue look like?_

An industry-standard ChaCha20-Poly1305 algorithm is used to encrypt and authenticate all data that requires decryption.  Previous versions used AES-256.

## Additional information

_(OPTIONAL) What other information can you provide about this issue?_
Source:
https://github.com/magento/magento2/blob/2.3.0/lib/internal/Magento/Framework/Encryption/Encryptor.php

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/systems/security/encryption-key.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
