### ISSUE TITLE
Feedback on page: /sales/quick-order.html

### ISSUE THREAD

**Issue by sethakkerman** [magento/merchdocs#197]
It would be helpful to see what default mobile views looked like for some of these pages that are typically wider than mobile devices.

**Comment by shrielenee** [comment]
Hey @sethakkerman --- Thanks for creating this issue. It seems like you are requesting that the screenshots in our MerchDocs pages. This isn't a current documentation initiative, and is more related to the work that our PWA (progressive web apps) team is doing.

Unfortunately, we cannot refactor all our screenshots at this time. We're going to close this issue at this time. If you would like to add more info and feel this issue needs to be recreated, you are more than welcome to. Thanks!
