### ISSUE TITLE
Product topics -- Improvements needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#2]
# Background

User feedback for product topics:

https://docs.magento.com/m2/ce/user_guide/catalog/product-create-configurable.html	
`In this you have not mention all tables name where configurable product save`

https://docs.magento.com/m2/ce/user_guide/catalog/product-create-simple.html
`"There's a problem in
Step 1: Choose the product type.
1. On the Admin sidebar, tap "Products. Then, choose Catalog." But rather it should be: 1. On the Admin sidebar, tap "Catalog. Then, choose products"."`

https://docs.magento.com/m2/ee/user_guide/catalog/product-gift-card-account-configuration.html	
`No info on how to DISABLE this function. Sort it out.`

https://docs.magento.com/m2/ee/user_guide/catalog/product-image-upload.html 
`cannot find the area icon in "images" tab`

https://docs.magento.com/m2/ce/user_guide/catalog/swatches.html	21 

`i am stuck in putting swatch i put 39 colors and after that its not going further...`

`Magento 2.2 no longer show original price for configurable products on category view if its child product has special price	(not sure if this is really related to this page or not)`

`This page on swatches only describes the Text-based swatch option.`

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

TBD

**Comment by shrielenee** [comment]
We do not document where the configurable products are stored in the user guide---that first line item is not needed for this issue. This MAY be a DevDocs addition, but is not applicable to Merch Docs.

**Comment by leslietilling** [comment]
Closing... too far out of date now
