### ISSUE TITLE
Feedback on Order update page

### ISSUE THREAD

**Issue by edwardbatchelor** [magento/merchdocs#204]
**I want to cancel an order but following your instructions below I run into a problem.  There is no Cancel option for me on my top line like your picture.**

/sales/order-update.html

To cancel an order:
Canceling an order changes its status from Pending to Canceled.

In the Orders grid, find the pending order to be canceled.

In the Action column, click View.

Click Cancel to cancel the order.

Cancel Order

The status of the order is now Canceled.

**Comment by shrielenee** [comment]
@ccondra Add the applicable labels first! :)

**Comment by ccondra** [comment]
We need to clarify that only orders with a status of "Pending" can be cancelled. This is explained in the [Order Processing](https://docs.magento.com/m2/b2b/user_guide/sales/order-processing.html) topic, but not well enough in the [Updating an Order](https://docs.magento.com/m2/b2b/user_guide/sales/order-update.html) (from the Admin).  Pending orders can be cancelled up to the time an invoice is generated. The Delete option no longer appears after an order is invoiced. After payment is processed, a credit memo must be generated to issue a refund.

**Comment by ccondra** [comment]
PR: https://github.com/magento/merchdocs/pull/290

**Comment by ccondra** [comment]
Completed and merged.
