### ISSUE TITLE
'Edit this page on GitHub' link from "Adobe Stock integration" and "Using Adobe Stock Images" sections leads to Page not found 404

### ISSUE THREAD

**Issue by chalov-anton** [magento/merchdocs#207]
# Bug report

## Description
'Edit this page on GitHub' link from "Adobe Stock integration" and "Using Adobe Stock Images" sections leads to _Page not found 404_

### Steps to reproduce
1. Navigate to Content - Content Elements - Pages - Media Storage - **Adobe Stock Integration** or **Using Adobe Stock Images**
2. Click **Edit this page on GitHub** link in the top right corner
![edit this page](https://user-images.githubusercontent.com/45624059/71000813-9acd4e80-20e4-11ea-9fef-2f2827e5da0a.png)

## Expected result
A Proper page on GitHub is opened

## Actual result
 a _404 This is not the web page you are looking for_ web page is opened 
![page not found](https://user-images.githubusercontent.com/45624059/71001031-15966980-20e5-11ea-8863-09db51d3a77e.png)

**Comment by konarshankar07** [comment]
I think this issue has been fixed. Please close the ticket

**Comment by leslietilling** [comment]
Page must exist in `master` for the "Edit this page in GitHub" to function. This new page was not merged until January for the 2.3.4. release. This now functions as designed.

closing issue.
