### ISSUE TITLE
Feedback on page: /catalog/product-create-configurable.html

### ISSUE THREAD

**Issue by chrystalgraham** [magento/merchdocs#219]
Hello,

The Product Variation Attribute Requirements attribute input types is incorrect. The only options are Dropdown, Visual Swatch and Text Swatch. 

![image](https://user-images.githubusercontent.com/36898600/71674963-b70af580-2d4a-11ea-8ee6-1180c2974249.png)

**Comment by ccondra** [comment]
This issue is complete. https://github.com/magento/merchdocs/pull/291
