### ISSUE TITLE
Clarify TAM information in /stores/compliance-ccpa-guide.html

### ISSUE THREAD

**Issue by dougkm** [magento/merchdocs#220]
"Magento Technical Account Manager"  Not all customers have a technical account manager/

Compliance requests should be submitted as support tickets.

**Comment by ccondra** [comment]
This has been clarified as follows:
"Merchants with stores hosted on Adobe Commerce Cloud can ask their Magento Technical Account Manager or Customer Support for help responding to consumer requests."
