### ISSUE TITLE
Explicitly connect this repository to docs.magento.com in README

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#223]
# Topic clarification/correction request

## Topic Link

N/A - this issue is about this project's README

## Description

I think it would be good to explicitly point out where the "production" version of this project is deployed / available. As a contributor and magento employee, that is obvious to me (e.g. https://docs.magento.com/m2/ee/user_guide et al) but I think as an outsider, it is not super clear based purely on the README of this repo.

## Possible solutions

I suggest we mention the final production URL somewhere in the README. Perhaps in the introductory sentence of the README? Something like "this project contains source code for the user guides available at docs.magento.com"?

## Additional information

I would give super bonus points if the process for deploying to the production site is described, though I understand perhaps that process contains Magento secret sauce and thus is not appropriate to publicize. In that case, perhaps a high-level description of the deployment process / deploy gatekeepers could be described? I.e. "deployment to docs.magento.com is gated by Maintainers A and B and we released on a bi-weekly schedule" or something to that effect.

**Comment by shrielenee** [comment]
@filmaj You're right. We need to add all three URLs to diff versions in the README.

**Comment by dshevtsov** [comment]
Also, note that the production site link is available in the **About** section on the main page of the repository.
