### ISSUE TITLE
Feedback on page: /catalog/category-permissions.html

### ISSUE THREAD

**Issue by misha-kotov** [magento/merchdocs#224]
Screenshot formatting issue in the middle of Step 1 (**Product Prices** heading)
![image](https://user-images.githubusercontent.com/18131925/71745226-24905200-2e2f-11ea-9414-be067862daea.png)

**Comment by shrielenee** [comment]
It seems as if this is an indentation problem, so it's showing code and not rendering proper text.

**Comment by ccondra** [comment]
Completed and merged. 
https://github.com/magento/merchdocs/pull/298
