### ISSUE TITLE
Creating a Widget -- add more examples

### ISSUE THREAD

**Issue by ccondra** [magento/merchdocs#229]
# Topic clarification/correction request
Step 3 of this topic should include examples of several types of widgets. At this time, there's a disconnect because steps 1 and 2 feature a CMS Static Block and Step 3 features a Catalog New Products List. 

## Topic Link
https://docs.magento.com/m2/ee/user_guide/cms/widget-create.html

## Description
Rather than remove the instructions in Step 3 for a new products list, which are correct, we should add more examples, starting with CMS Static Block.  
## Possible solutions
It would be good to include each major type of widget, such as a block, list, and link.

**Comment by danidelcar** [comment]
Hi @ccondra do you think we could open this issue to community contribution?, seems fairly easy to get a good first issue?, thanks!

**Comment by hickskenh** [comment]
moved to https://jira.corp.adobe.com/browse/COMDOX-233
