### ISSUE TITLE
Feedback on page: /catalog/inventory-configure-distance-priority.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#232]
"Import geocodes for Inventory Management" link redirect to https://devdocs.magento.com/#/individual-contributors.

To reproduce.

Goto >> https://docs.magento.com/m2/ee/user_guide/catalog/inventory-configure-distance-priority.html#step-1-download-and-import-geocodes

Click on See DevDocs Import geocodes for Inventory Management link redirect to inappropriate location.

**Comment by shrielenee** [comment]
This is potentially a URL link/redirect issue. Test and fix the errant link.
