### ISSUE TITLE
Feedback on page: /catalog/product-create-grouped.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#236]
Screenshots are not as per group product, price attribute should not be visible.

To reproduce see images on https://docs.magento.com/m2/ee/user_guide/catalog/product-create-grouped.html 

1. https://docs.magento.com/m2/ee/user_guide/images/images/product-create-choose-attribute-set.png

2. https://docs.magento.com/m2/ee/user_guide/images/images/product-create-store-view-choose.png

Which are not as per group product, In group product price is showing in screenshot as per my knowledge should not be there. 

![image](https://user-images.githubusercontent.com/19387846/72133055-8eb47400-33a6-11ea-98a7-999d5a9a82ff.png)

**Comment by ccondra** [comment]
This issue is complete.
