### ISSUE TITLE
Feedback on page: /stores/attributes-rating.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#237]
Should be brief description regarding **Is Active** in **Rating Visibility** section, As new Magento user or merchant who referring user guide will gain more understanding why and how to use of **Is Active** in rating section.

Page reference - https://docs.magento.com/m2/ee/user_guide/stores/attributes-rating.html

**Comment by pawankparmar** [comment]
@jcalcaben, Please assign this issue to me.
Thank you.

**Comment by pawankparmar** [comment]
@jcalcaben , this is fixed in #372 so we close this issue

**Comment by pawankparmar** [comment]
@jcalcaben, issue is fixed! could you please close issue ? thank you.

**Comment by jcalcaben** [comment]
Thanks @pawankparmar !
