### ISSUE TITLE
Feedback on page: /marketing/price-rule-multiple-sku.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#238]
Hierarchy is showing for **Catalog Price Rule** but content showing is **Cart Price Rules**.

To reproduce 

Goto >> https://docs.magento.com/m2/ee/user_guide/marketing/price-rule-multiple-sku.html#step-2-apply-a-price-rule-to-multiple-skus

This portion is included in **Catalog Price Rule** but content shows configuration is for  **Cart Price Rules**(On the Admin sidebar, click Marketing. > Promotions > Cart Price Rules). 

Documentation for **Cart Price Rules** and **Catalog Price Rule** should be in different hierarchy.

Please check screenshot for more clear picture.

![image](https://user-images.githubusercontent.com/19387846/72179411-d40a8d00-340a-11ea-9840-4350571d5eb2.png)

**Comment by ccondra** [comment]
This topic is about Catalog Price Rules, so I reworked it accordingly.

**Comment by ccondra** [comment]
This issue is complete. https://github.com/magento/merchdocs/pull/390
