### ISSUE TITLE
Convert HTML tables - reports folder

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#24]
# Request

## Description

All topics in the src/reports folder to be reviewed and all embedded HTML tables converted to Markdown. Most of these pages are in the Operations/Reports section, but some could be mapped to other sections. 

## Additional information

Some tables have nested sub-tables. Review items in the src/configuration folder for formatting examples to handle those items

**Comment by atwixfirster** [comment]
Hi, @leslietilling !

I've checked all files in the `src/reports` folder and did not find any file with  HTML tables.

Thank you!
