### ISSUE TITLE
Feedback on page: /marketing/price-rules-cart-create.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#240]
Issue is with **Click the “more” (…) link, and enter >100. This condition requires the total quantity of the cart to be greater than 100.**

To reproduce 

Goto >> https://docs.magento.com/m2/ee/user_guide/marketing/price-rules-cart-create.html#step-2-describe-the-conditions

Find in page - "Click the “more” (…) link, and enter >100. This condition requires the total quantity of the cart to be greater than 100."

Please refer screenshot which can be create potential issue on apply shopping cart rule and sub totals. should not apply >100 in textbox shold be proper as per Magento standards. 

![image](https://user-images.githubusercontent.com/19387846/72183571-577cac00-3414-11ea-8dc5-3b069e270e10.png)

It should be as per below screenshot

![image](https://user-images.githubusercontent.com/19387846/72183982-5435f000-3415-11ea-928e-2c1d2af6ff40.png)

**Comment by hickskenh** [comment]
created PR #352.
