### ISSUE TITLE
Feedback on page: /system/permissions-user-roles.html

### ISSUE THREAD

**Issue by chakravarthykalyan90** [magento/merchdocs#248]
Screenshot provided under "Step 2: Assign resources" > "Set Role Scopes to one of the following" is not related to Magento 2.3.3 open source. Store selection option is there only in the commerce edition. Magento 2.3.3 open source edition don't have option to select the stores while setting the role scopes. Please remove and update it with open source screenshot.

page Link: https://docs.magento.com/m2/ce/user_guide/system/permissions-user-roles.html

![image](https://user-images.githubusercontent.com/3271931/72249684-df82d180-361f-11ea-844b-329b038b634e.png)

**Comment by karyna-tsymbal-atwix** [comment]
I think I can fix this issue, could you please assign it to me?

**Comment by hickskenh** [comment]
Hey @karyna-tsymbal-atwix and thank you for your feed back.  correcting the issue requires the addition of condition tags for the Commerce edition.  If you want to make the edits, you can click the `Edit this page in Github` link in the upper right corner, make your edits, and submit a PR.  

I need to take a better look at the difference between the editions to fully determine what is needed, but if you already know, we welcome contributions.

**Comment by pawankparmar** [comment]
@hickskenh @dobooth, please assign this issue to me.
Thank you.

**Comment by hickskenh** [comment]
issue has been assigned.   look forward to your PR

**Comment by chakravarthykalyan90** [comment]
> issue has been assigned. look forward to your PR

Hi @hickskenh did you assign me by mistake?

**Comment by hickskenh** [comment]
yes, i totally did.  Sorry about that.  Updating now.  Trying to do too many things at once. Thanks for letting me know

**Comment by chakravarthykalyan90** [comment]
> yes, i totally did. Sorry about that. Updating now. Trying to do too many things at once. Thanks for letting me know

No problems @hickskenh

**Comment by mamsincl** [comment]
issue still exists

**Comment by hickskenh** [comment]
@pawankparmar did you still want to handle this issue?

**Comment by pawankparmar** [comment]
@hickskenh, Yes I am. I will create PR soon. thank you.

**Comment by dobooth** [comment]
Fixes as above.
