### ISSUE TITLE
Missing info about Currency Converter API

### ISSUE THREAD

**Issue by keharper** [magento/merchdocs#249]
# Bug report

## Description

In https://github.com/magento/magento2/pull/24008, the contributor added the *API Key* field to the Stores > Settings > Configuration > General > Currency Setup > Currency Converter API dialog. It turns out that the Currency Converter API section isn't documented at all.

### Steps to reproduce

1. On a 2.3.4 build, go to Stores > Currency > Currency Rates
2. Select Currency Converter API from the Import Service drop-down
3. Go to Stores > Settings > Configuration > General > Currency Setup > Currency Converter . There is now a Currency Converter API 

Note: The current documentation has a section for Yahoo Finance Exchange. It appears this option was removed in the 2.2 release.

**Comment by Ketika** [comment]
Please assign this ticket to me. I would like to work for the same

**Comment by keharper** [comment]
It's yours, @Ketika
