### ISSUE TITLE
Feedback on page: /customers/name-address-options.html

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#250]
Needed improvement on this page.

To reproduce 

Goto >> https://docs.magento.com/m2/ee/user_guide/customers/name-address-options.html

1) Find line **In the Suffix Dropdown Options field, enter each prefix that you want to appear in the list, separated by a semicolon.** in page.

- Need to replace with **In the Suffix Dropdown Options field, enter each suffix that you want to appear in the list, separated by a semicolon.**

2) Find line - **Set Show Telephone to Yes.**

- in admin area options available are as below.

1) No
2) Optional
3) Required

- Should be corrected instead of **Yes**.

![Telephone](https://user-images.githubusercontent.com/19387846/72282633-0dd5d080-3663-11ea-8cdc-4eb68e7fd0f6.png)

3) Find line - **Set Show Company to Yes.**

- in admin area options available are as below. 

1) No
2) Optional
3) Required

- Should be corrected instead of **Yes**.

![Company](https://user-images.githubusercontent.com/19387846/72282744-4bd2f480-3663-11ea-8544-12cb4e4f5b8b.png)

4) Find line - **Set Show Fax to Yes.**

- in admin area options available are as below.

1) No
2) Optional
3) Required

- Should be corrected instead of **Yes**.

![Fax](https://user-images.githubusercontent.com/19387846/72282781-67d69600-3663-11ea-8472-c31618292f48.png)

**Comment by ccondra** [comment]
This issue is complete.  https://github.com/magento/merchdocs/pull/399
