### ISSUE TITLE
Links redirection issue

### ISSUE THREAD

**Issue by denish-c-vachhani** [magento/merchdocs#265]
# Bug report

## Description

Link of "Avalara" and "Magento Technology Partner" not redirect as expected.

### Steps to reproduce

1. GOTO >> https://docs.magento.com/m2/ee/user_guide/system/data-transfer-tax-rates.html
2. Click on "Avalara" and "Magento Technology Partner".
3. Redirect to "https://magento.com/partners/choose". 

## Expected result

- Should be redirect to proper search result page or given link page.

## Possible solutions

- Add related link href.

## Additional information

![image](https://user-images.githubusercontent.com/19387846/72461263-9f287c80-37f4-11ea-9eac-e25e9c7822cc.png)

**Comment by hickskenh** [comment]
https://www.avalara.com/us/en/index.html

**Comment by hickskenh** [comment]
This issue is resolved with PR#315.
