### ISSUE TITLE
Convert HTML tables - system folder

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#27]
# Request

## Description

All topics in the src/system folder to be reviewed and all embedded HTML tables converted to Markdown. Most of these pages are in the Operations/System section, but some could be mapped to other sections. 

## Additional information

Some tables have nested sub-tables. Review items in the src/configuration folder for formatting examples to handle those items

**Comment by edenduong** [comment]
@magento I am working on it

**Comment by edenduong** [comment]
How to assign to this issue ? Thanks

**Comment by krisdante** [comment]
@magento I am working on it
