### ISSUE TITLE
Links to Marketplace user docs - 404

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#28]
# Bug report

## Description

Link to Marketplace user docs produces a 404 "Out of Stock" page

### Steps to reproduce

1. Go to https://docs.magento.com/m2/ee/user_guide/magento/magento-marketplace.html
2. Locate "For step-by-step installation instructions, see Marketplace User Guide." at the bottom of the page.
3. Click link.

## Expected result

This should open the correct page in the Marketplace guide.

https://docs.magento.com/marketplace/user_guide/buyers/install-extension.html

## Possible solutions

Update link to point to the correct published page

## Additional information

TBD

**Comment by atwixfirster** [comment]
`Marketplace Quick Tour` link is also wrong on that page. I've set https://docs.magento.com/marketplace/user_guide/buyers/install-extension.html for that link

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/merchdocs/pull/33

**Comment by shrielenee** [comment]
Fixed by #33
