### ISSUE TITLE
Clarify multiple discount workflows on /marketing/price-rules-cart-create.html

### ISSUE THREAD

**Issue by ascottfuji** [magento/merchdocs#286]
The description of Priority & Discard Subsequent Rules could use some exmaples to better explain expected behaviour.  For example let's say I have a $6.00 off rule and a 50% rule that apply to an 11oz coffee mug that costs $10.00.

If both rules have a priority of 1: 
1. Are both rules applied to the product?
2. If the answer to 1 is yes, then in what order are they applied?  This is important as one combination will result in the mug costing $2.00 and the other combination will result in a free mug.
3. If the answer to 1 is no, then which promotion will be applied?

If both rules have a priority of 1 and one has the Discard Subsequent Rules set to true, then what happens?

**Comment by hickskenh** [comment]
Hey @ascottfuji.  thanks for your feedback.  there is a similar topic in the Amazon channels documentation that describes this a little better.  i'll update the Cart Rules topic with the same information.

Multiple price rules can apply to the same purchase, unless you set **Discard Previous Price Rules** in the **Action** section to `Yes`.

For **Discard Subsequent Rules**, select an option.

**Yes**: Choose when you do not want any other pricing rules that may apply to a product to be applied. Discarding subsequent rules means that, in the event that multiple pricing rules apply to the same product, only the pricing rule with the highest defined priority (in a rule's **Priority** field) will be applied to a qualifying product. This prevents multiple pricing rules from stacking and providing unintended additional discounts.

**No**: Choose when you want to allow multiple pricing rules to apply to the same product. This could result in stacking and providing multiple discounts applied to your listing price.

**Note**: To discard subsequent rules, a pricing rule must use your defined priorities which are set in the **Priority** field.

Does this answer your question until i can update the Cart Price Rule topic?

**Comment by hickskenh** [comment]
submitted PR#299 for this.
