### ISSUE TITLE
Feedback on page: /reports/advanced-reporting.html

### ISSUE THREAD

**Issue by jagdishdots** [magento/merchdocs#296]
Advance Reporting Subscription not enabled Magento 2.3.2

I have configured the advanced reporting on the Magento website (community version 2.3.2). after 3-4 days status is showing pending.

I have configured all the things and reauthorize the Integration user but the user is still in reauthorizing mode.

![advance-reporting](https://user-images.githubusercontent.com/4446150/73442747-61426100-437b-11ea-8d13-5f3227cbff43.png)

![url-options](https://user-images.githubusercontent.com/4446150/73442765-6bfcf600-437b-11ea-947d-aed21428ffd4.png)

![integration](https://user-images.githubusercontent.com/4446150/73442778-728b6d80-437b-11ea-9dd4-5b31d8a0bf59.png)

**Comment by hickskenh** [comment]
Hey @jagdishdots. Thank you for the feedback.  I'm not sure this is a docs issue, you may need to contact support.  But based on your screen shots, your integration is not in Active status and you need to follow the steps to reauthorize the user on this page: https://docs.magento.com/m2/ce/user_guide/reports/advanced-reporting.html#requirements.

**Comment by jagdishdots** [comment]
@hickskenh 
Thanks for your reply.

I have verified the details after a click on reauthorize and details are the same. but it is still in the pending state

**Comment by hickskenh** [comment]
@jagdishdots 
Hey.  I had another writer review this ticket.  They agreed that this appears to be a support issue. If you need a support contact, let me know.  And if support determines the issue is something we need to document in a note or an update, please open another ticket.

**Comment by jagdishdots** [comment]
Hi @hickskenh 

Please provide the support on this issue. I have already debugged the issue but didn't find any solution.

**Comment by hickskenh** [comment]
To get answers to your questions, contact [Magento Support](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets)---They should be able to help you with this! Let us know if you have anymore questions.

**Comment by hickskenh** [comment]
Hey @jagdishdots. i just saw a separate PR that will update the Advanced reporting topic.   below is the updated text.  It may not apply to your situation, but wanted to make you aware.

Advanced Reporting can be used only with Magento installations that have used only a single [base currency](https://docs.magento.com/m2/ce/user_guide/stores/currency-configuration.html), and that have a history of orders processed with the same base currency. Advanced Reporting will not work if you change the base currency and as a result, have orders processed with different base currencies.

**Comment by jagdishdots** [comment]
Hi @hickskenh ,

we are using only single currency USD in our website.
