### ISSUE TITLE
Configuration Scope -- Improvements needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#3]
# Background

User feedback for scope topic:

https://docs.magento.com/m2/ce/user_guide/configuration/scope.html	

`entering new customer will not save`	

`not expicit enough, doesn't tell the scope order. what overwrites what`

`very deficult`

`It doesn't really help someone who doesn't know the basics`	

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

TBD

**Comment by dobooth** [comment]
Closed by over-aggressive Github actions.

**Comment by shrielenee** [comment]
Hey @mmansoor-magento --- The page you listed for this PR is a top-level index page. Can you find the specifically applicable page and add more info? Thanks!

**Comment by jeff-matthews** [comment]
@shrielenee, `mmansoor-magento` isn't the right person to ask. That's the account Mehryar used to batch migrate issues between repos at some point. I don't know who the original reporter is.

**Comment by shrielenee** [comment]
Oohhh ok @jeff-matthews. Thank you.

**Comment by leslietilling** [comment]
Closing... too far out of date now from original customer comments in Hotjar.
