### ISSUE TITLE
Feedback on page: /sales/order-update.html

### ISSUE THREAD

**Issue by jerdek** [magento/merchdocs#347]
It can be a bit confusing trying to distinguish the difference between an order in pending and an order in processing. Pending I believe refers to the database state of the order. Pending orders can be edited, but it should be more clear what the front end status would be for an order that is able to be edited.

**Comment by hickskenh** [comment]
Thank you @jerdek for your feedback.  The short answer to your question is that the sales order has a status of “Pending” until payment is received. While in `Pending` status, orders can be edited or canceled up until the time that payment is received and an invoice is generated.

Check out the **Processing Orders** topic for more information:  https://docs.magento.com/m2/ee/user_guide/sales/order-processing.html

for the page you reported, i'll add a few notes to clarify.

**Comment by hickskenh** [comment]
PR#351 created to add clarification text

**Comment by shrielenee** [comment]
This issue was resolved via the mentioned PR. I am closing this.
