### ISSUE TITLE
Remove quotes from page titles

### ISSUE THREAD

**Issue by shrielenee** [magento/merchdocs#35]
# Bug report

## Description

There are many instances where the reference to a page is included in quotes, like `"Privacy Policy" page`. We need to remove those quotes.

### Steps to reproduce

Many pages are affected, including https://docs.magento.com/m2/ce/user_guide/cms/pages-core.html.

## Expected result

No other instances of references to pages/views remain in quotes.

## Additional information

If a pull request for this issue is large, break it up into multiple PRs for ease of reviewing.

**Comment by filmaj** [comment]
#54 was merged and so I think this can now be closed.

**Comment by leslietilling** [comment]
Not sure if all instances were addressed, but tried some searches and did not find any additional items. Closing now but we can reopen if needed.
