### ISSUE TITLE
Sync rake tasks with devdocs: 'test:md', 'check' prerequisites

### ISSUE THREAD

**Issue by dshevtsov** [magento/merchdocs#363]
There is an important update in rake tasks introduced in magento/devdocs#6677. 

Implement the corresponding changes in this project. For detailed information, see commits at the PR mentioned above.

**Comment by dshevtsov** [comment]
@dobooth do you have any blockers with this?

**Comment by dobooth** [comment]
https://github.com/magento/merchdocs/pull/471
