### ISSUE TITLE
Feedback on https://docs.magento.com/m2/ee/user_guide/magento/magento-account-share.html

### ISSUE THREAD

**Issue by duffner** [magento/merchdocs#379]
Please provide instructions on how "Sharing" works, as an entire page is missing from the Dashboard.  So many customers don't understand how to share their Enterprise/Cloud account with an Agency, and there isn't clear instructions available.

**Comment by shrielenee** [comment]
Hello! Are you speaking of the Dashboard in the Magento UI @duffner ? What part of the instructions in the page you reference  https://docs.magento.com/m2/ee/user_guide/magento/magento-account-share.html are not clear or don't work? 

We just need a bit more information to understand your issue. Thanks!

**Comment by dobooth** [comment]
Closing as abandoned.

**Comment by duffner** [comment]
Team, 
I filtered GitHub Responses, I didn't see it!!  Sorry about that. I'm referring to how "Sharing Works" what are all the "Checkboxes" what do they do, and how do they impact sharing. 

![screencapture-account-magento-grantor-manage-add-2020-03-26-11_36_48](https://user-images.githubusercontent.com/7387019/77671810-1c3f4300-6f56-11ea-9458-d719f645de0b.png)
