### ISSUE TITLE
SEO topics -- Improvements needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#4]
# Background

User feedback for SEO topics:

https://docs.magento.com/m2/ce/user_guide/marketing/url-rewrite-create.html
`This page introduces the "URL Rewrite Tool" but does not explain where the tool is.`

https://docs.magento.com/m2/ce/user_guide/marketing/seo-best-practices.html . 
`There are no "SEO Best Practices" Listed on this page.`

https://docs.magento.com/m2/ee/user_guide/marketing/sitemap-xml.html
`This page makes no reference to the DevDocs that cover required folder locations for Sitemap settings if you are a Cloud Customer: https://devdocs.magento.com/guides/v2.2/cloud/trouble/robots-sitemap.html Had to raise a support ticket to find this out"`

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

More defined "best practices"

Other improvements TBD

**Comment by leslietilling** [comment]
Closing.... too far out of date for original customer comments in Hotjar
