### ISSUE TITLE
Steps to create a credit-memo for "Online" refund are wrong

### ISSUE THREAD

**Issue by lazyguru** [magento/merchdocs#401]
# Bug report

## Description
The steps outlined on this page: https://docs.magento.com/m2/ce/user_guide/sales/credit-memo-create.html for issuing a credit memo (refund) are incomplete.  While the steps are _technically_ correct for creating a credit memo, they don't do what most merchants would expect.

### Steps to reproduce

The current instructions show how you can issue a refund by creating a credit memo from the "Order View" page. However, that will only allow for "Offline refunds".

## Expected result

To issue an "Online" refund, the credit memo must be created from the "Invoice view" page.

## Possible solutions

Update the instructions to walk the user through selecting an invoice that is attached to the order and THEN create the credit memo.

## Additional information

This is causing a lot of confusion with merchants that are trying to issue refunds for "online" payment methods.

**Comment by ccondra** [comment]
PR:  https://github.com/magento/merchdocs/pull/409

**Comment by ccondra** [comment]
This issue has been addressed.

**Comment by lazyguru** [comment]
Thank you @ccondra!
