### ISSUE TITLE
Need to document dashboard charts improvement

### ISSUE THREAD

**Issue by jeff-matthews** [magento/merchdocs#403]
# New topic request

## Description

In the scope of magento/magento2#26923, a new library was added to improve the UI (i.e., dashboard charts).

We need to document the dashboard charts improvement.

Will be the part of the 2.4.0 release.

## Content checklist

- [ ] The topic provides an explanation of how improved dashboard charts work.
- [ ] The topic provides steps for enabling charts..
- [ ] The topic contains examples that shows new dynamic dashboard charts.

## Additional information/resources

@lenaorobei is the original reporter and created an issue in the devdocs repo: magento/devdocs#6830.
This actually impacts the Admin in a visual way, so it belongs in the merchdocs repo instead.

**Comment by leslietilling** [comment]
Looks like this is complete with this PR: https://github.com/magento/merchdocs/pull/519

Closing
