### ISSUE TITLE
Update Export topic

### ISSUE THREAD

**Issue by pawan** [magento/merchdocs#406]
Following points need to be update in Document as per Magento 2.3.x.

- Add additional Entity Type like **Advanced Pricing**, **Stock Sources**
- As now latest magento does not direct download file and add them to queue
- How Admin can get exported file

Affected topic: https://docs.magento.com/m2/ce/user_guide/system/data-export.html

**Comment by pawankparmar** [comment]
@ccondra, Any updates ?

**Comment by pawan** [comment]
@ccondra , please assign this issue to me.

**Comment by pawan** [comment]
@magento I am working on this
