### ISSUE TITLE
Clarify how to regenerate URL rewrites

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#414]
# Topic clarification/correction request

Add workaround information for regenerating URL rewrites

## Topic Link

https://docs.magento.com/m2/ce/user_guide/stores/admin-actions-control.html
https://docs.magento.com/m2/ce/user_guide/marketing/url-rewrite.html

## Question
URL rewrites have been broken or deleted.

Now all products URLs are displayed as http://www.example.com/catalog/category/id/6

How to regenerate URL rewrites?

## Answer
Unlike Magento 1, Magento 2 does not have a separate URL rewrite Indexer.

In order to create a single URL rewrite, please refer to http://docs.magento.com/m2/ce/user_guide/marketing/url-rewrite-create.html

There is a workaround that allows to quickly fix URL rewrites for all products simultaneously.

Steps

1. Open Admin > Catalog > Products
2. Select All products for which you want to update URL rewrites
3. In Actions dropdown, select Update Attributes to perform mass update
4. Switch to Websites tab
5. In 'Add Product To Websites' section select all websites for which you want to restore URL rewrites. 
6. Note that all selected products will be re-added to the selected websites and URL rewrites will be regenerated.

## Possible solutions

Consider adding the workaround to regenerate URL rewrites above to one of the affected topics

## Additional information

Moved from the KB Jira project after establishing KB scope. This request for a KB was determined to be out of scope for the KB, but within scope for merchdocs.

Moved from MAGEDOC-3734

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
@leslietilling The workaround steps are on the page (https://docs.magento.com/user-guide/marketing/url-rewrite-update-all.html) which is already specified as a link in the URL-rewrite file (https://docs.magento.com/user-guide/marketing/url-rewrite.html).

**Comment by sathiyaaa** [comment]
@leslietilling Any updates on this?

**Comment by leslietilling** [comment]
Looks like this was already done.
