### ISSUE TITLE
Add schema for concepts such as tax class, tax rule, etc. to Tax classes topic

### ISSUE THREAD

**Issue by Safegear** [magento/merchdocs#428]
A squema would be nice.

**Comment by shrielenee** [comment]
Regarding: https://docs.magento.com/m2/ee/user_guide/tax/tax-class.html

**Comment by shrielenee** [comment]
Can you please provide more information about what you need @Safegear ?

**Comment by shrielenee** [comment]
Per your other PR, you are requesting info: "It would be nice to have a squema to understand the different concepts. tax class, tax rule, tax rate, countries... etc."

I'm closing the second almost identical issue and request more info here! Thank you!

**Comment by shrielenee** [comment]
Given we haven't received an answer to our question in two weeks, and have little information to actually go on, I will be closing this issue. If you feel it warrants our work please open another issue! Thanks!
