### ISSUE TITLE
Edit Customer groups topic to include steps to create customer groups for discounts

### ISSUE THREAD

**Issue by Safegear** [magento/merchdocs#429]
There is no steps to create a 

Customer groups related to a specific discounts available.

Regarding: https://docs.magento.com/m2/ee/user_guide/customers/customer-groups.html

**Comment by carolinabett** [comment]
Hello, I can't attribute myself to this issue. :(

**Comment by hickskenh** [comment]
Hey @carolinabett, i assigned the issue to you.  See if that resolves your issue.
