### ISSUE TITLE
Media Gallery topic

### ISSUE THREAD

**Issue by lenaorobei** [magento/merchdocs#444]
# New topic request

## Description

Add new topic about new Media Gallery implemented in the scope of [Adobe Stock Integration project](https://github.com/magento/adobe-stock-integration)

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains examples that shows ____.
- [ ] The tutorial should walk-through a complicated process.
- [ ] Other (please specify)

## Additional information/resources
See related stories in the project https://github.com/magento/adobe-stock-integration/issues?q=is%3Aissue+is%3Aclosed+label%3AStory+

**Comment by tkacheva** [comment]
h2. what to cover
1. Enabling new media gallery in Magento Admin. 
2. Reindexing images uploaded to the server 
3. Reindexing images after content import
4. Uploading images to  the Media Gallery 
+ scope in the Phase 3 stories

**Comment by leslietilling** [comment]
This was addressed by @gabrieldagama  in #507. Closing this issue
