### ISSUE TITLE
Cart Sidebar (MiniCart) - include "My Cart Link" Instructions

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#46]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/sales/cart-link.html

https://docs.magento.com/m2/ee/user_guide/sales/cart-sidebar.html

## Description

At this time, the My Cart Link instructions and the Cart Sidebar are separate topics. My Cart Link does have a link to the Shopping Cart Sidebar topic, but not the other way around. Ideally these should be combined into a single topic.  Although they are separate sections in the configuration UI, they are so closely related that it makes sense to combine them.

[https://docs.magento.com/m2/ee/user_guide/sales/cart-link.html]

[https://docs.magento.com/m2/ee/user_guide/sales/cart-sidebar.html]

## Possible solutions

As a quick fix, add a link to the Shopping Cart Sidebar topic back to My Cart Link topic.
The better solution is to combine the two topics by adding the My Cart Link info into the Shopping Cart Sidebar topic, and redirecting My Cart Link. 
This change needs to be made to the CE/EE/B2B user guides.

This issue was reported by Olena Tkacheva. She also sent this link to a third-party tutorial on the subjec, and suggested that we might have something similar.  [https://www.tutorialspoint.com/magento/setup_check_out_options.htm]

**Comment by rodrigowebjump** [comment]
I will work in this issue

**Comment by hickskenh** [comment]
Hey @rodrigowebjump  i've assigned this ticket to you.  Thanks.

**Comment by rodrigowebjump** [comment]
@leslietilling I do not have sure that we should merge these pages.
All other cart configurations, including the thumbnail config are in separated pages. Merge all info in one page will make the configuration doc page too long.

Maybe an option for this is improve the page https://docs.magento.com/m2/ee/user_guide/sales/cart-configuration.html including more information, explaining an overview about the options the merchant has and some screenshots.

Them reorder the cart thumbnail section after the Cart Sidebar to make the sequence of the configurations more natural.

What do you think?

**Comment by meker12** [comment]
Hello @rodrigowebjump -- Our Magento docs team is jointly supporting the contribution day, so I'll respond to this on behalf of @leslietilling.   Your plan sounds like a good one. We look forward to reviewing your PR.

**Comment by leslietilling** [comment]
@rodrigowebjump Do you have a PR for this?
