### ISSUE TITLE
Buy X Get Y Free - correction

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#462]
# Bug report

## Description

This issue came to the support team through a management escalation. A customer followed the steps to create a Buy 1 Get 1 promotion from this page..

https://docs.magento.com/m2/ee/user_guide/marketing/price-rules-cart-buy-x-get-y-free.html

They claim that the promotion did not work. Initially, we thought it was a bug after testing it out on our end. However, upon further review, it looks like the customer made a configuration error. The steps provided in the user doc page is incorrect in "Step 3: Define the actions". Specifically, in Step 1c..

To limit the number of discounts that can be applied when the condition is met, enter the number in the Maximum Qty Discount is Applied To field. **For example, enter “1” to discount only one item.**

That last sentence is incorrect. The value for "Maximum Qty Discount is Applied To" field must be calculated from a formula that is provided further down the page..

```
Formula = (X+Y) * (M/Y)
 Where
 X = number of items purchased
 Y = number of free items
 M = Maximum number of free items allowed
```

## Possible solutions

Recommendations: Remove the incorrect sentence and replace it with wording to direct the reader to the formulas further down the page.

## Additional information

This was migrated from internal MAGEDOC issue (MAGEDOC-3863

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
