### ISSUE TITLE
Update to Sharing your account topic

### ISSUE THREAD

**Issue by hguthrie** [magento/merchdocs#464]
Feedback on page: /magento/magento-account-share.html

Received a request in email to update information about Sharing Access:

> I was wondering if I could request a small update to DevDocs here on Sharing Your Account
> This paragraph needs to be added:
> 
> “After receiving shared access, the user needs to log in to Magento.com Account page, navigate to Shared Access, and click on the Support tab. This only needs to be done the first time. Doing this will ensure that the Magento Help Center is configured properly via the SSO call from Magento.com to Magento Help Center.” 

A similar update has been made to [the KB Article titled Provide shared access](https://support.magento.com/hc/en-us/articles/360020694351-Provide-shared-access-to-Magento-Account).

**Comment by dineshvb** [comment]
@leslietilling Can I take this issue?

**Comment by leslietilling** [comment]
@dineshvb If you have all you need to work, then that should be fine. If you need to update any screens, make sure that there are no personal account details visible. We usually blur those items as needed.

**Comment by dineshvb** [comment]
@magento I am working on this
