### ISSUE TITLE
Add info about how to create and use a category attribute

### ISSUE THREAD

**Issue by Safegear** [magento/merchdocs#465]
Understand how to create and  use a category attribute

Regarding: https://docs.magento.com/m2/ee/user_guide/catalog/categories.html

**Comment by shrielenee** [comment]
Are you looking for something like this @Safegear? https://devdocs.magento.com/guides/v2.3/ui_comp_guide/howto/add_category_attribute.html

CC @leslietilling

**Comment by shrielenee** [comment]
Hello! We are closing this issue due to non-response and inactivity. If our response did not answer your question please feel free to open another issue.
