### ISSUE TITLE
Improve Top Navigation content

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#47]
# Topic clarification/correction request

Multiple feedback comments about the Top Navigation. This appears to be something where users need extra help/clarification. 

## Topic Link

 https://docs.magento.com/m2/ce/user_guide/catalog/navigation-top.html -->  comments come from this page

https://docs.magento.com/m2/ee/user_guide/catalog/navigation.html --> could be that they are not looking at this page to gain a full understanding

## Description

Comments submitted:

`"doesnt explain how the top navigation works.
followed this through and still no top nav bar!"`

`There is no navigation. Is this a bug? I cant find any way to add any kind of navigtion to the site. I created lots of pages, categories and products, but without navigation, or any way to show a list of categories, how can the user find them?`

`This did not solve my problem. My subcategories still did not show up.`

**Comment by ccondra** [comment]
There is also a problem with the responsiveness of the hamburger menu. For certain viewport dimensions, there is no usable top navigation or left nav.

**Comment by irenelagno** [comment]
@magento I am working on this

**Comment by EvheniiaKolkhiieva** [comment]
@magento I am working on this
