### ISSUE TITLE
Improvement needed - dynamic blocks assoc with promotion rule

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#48]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/cms/dynamic-blocks-price-rules.html

## Description

The association between dynamic block and a promotion rule  is not clear. It should specify what it actually does to the block and to the rule

**Comment by tkacheva** [comment]
The dynamic block is displayed only when the rule fires. If the promo is targeted to a segment A, the block is shown to segment A. If the promo is not active, the block is not displayed
