### ISSUE TITLE
Rich Snippets needs details for entity metadata

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#480]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/marketing/meta-data.html

## Description

From customer:

The "Rich Snippets" section is very high level. Where can I find more information about which schema.org metadata is output for each of the Entities (Product, Category, Page), and under what circumstances?

Advised to browse codebase to get an idea and merchant replied:

I'm not a developer and don't have either the skills or access to trawl through code for this information (which is why I'm reaching out to you for this information). 

I didn't find much of anything to share, please provide anything possible, thanks.

## Possible solutions

Update topic to include details of the metadata outputs for each of the entities

**Comment by hickskenh** [comment]
moved to comdox #235 - https://jira.corp.adobe.com/browse/COMDOX-235
