### ISSUE TITLE
Feedback on page: /payment/paypal-credit.html

### ISSUE THREAD

**Issue by Rykh** [magento/merchdocs#49]
I found the deprecated documentation part on this page: https://docs.magento.com/m2/ee/user_guide/payment/paypal-credit.html

Stores > Settings > Configuration > Sales > Payment Methods > Paypal Express Checkout > Enable Paypal Credit  does not exist since Magento 2.3.1. This configuration was removed in scope of MC-10850

This functionality is not needed, Credit is enabled by default. 

For disabling this functionality please open Stores > Settings > Configuration > Sales > Payment Methods > Paypal Express Checkout > Basic Settings - PayPal Express Checkout > Frontend Experience Settings > Features

**Comment by hickskenh** [comment]
https://docs.magento.com/m2/ee/user_guide/payment/paypal-express-checkout.html

Step 7 here needs to be changed from paypal credit to "Enable In-Context Checkout Experience"

![image](https://user-images.githubusercontent.com/46905350/67599337-746ae280-f735-11e9-80d2-cb816052157f.png)

**Comment by hickskenh** [comment]
https://docs.magento.com/m2/ee/user_guide/payment/paypal-credit.html

topic needs to stay in TOC.  intro info is still valid.   remove Enable section/steps.   add "Paypal Credit is enabled by default when Paypal Express Checkout is enabled. To disable Paypal Credit, see the disable function in **Stores** > _Settings_ > **Configuration** > **Sales** > **Payment Methods** > **Paypal Express Checkout** > **Advanced Settings** > **Frontend Experience Settings** > **Features**."

**Comment by hickskenh** [comment]
duplicate magedoc ticket 4128.

**Comment by hickskenh** [comment]
Fixed with PR 125

**Comment by hickskenh** [comment]
Fixed with PR 125
