### ISSUE TITLE
Review table screenshots for clarity and relevance in data-csv.html topic

### ISSUE THREAD

**Issue by radovagas** [magento/merchdocs#499]
The table "Exported Product CSV in OpenOffice Calc" on Working with CSV Files doesn't contains a correct data.

https://docs.magento.com/m2/ee/user_guide/system/data-csv.html

**Comment by shrielenee** [comment]
Hello @radovagas --- Do you mean that the screenshots are outdated? Thanks!

**Comment by radovagas** [comment]
hello @shrielenee 
I mean the contains. Have a look at columns: name, description, short_description...

**Comment by erikmarr** [comment]
Our recommendation is to remove these screenshots from this topic. We can discuss the structure without showing images.

**Comment by chiranjeevi-cj** [comment]
@shrielenee Should remove those screenshots?

**Comment by AndreyChorniy** [comment]
Hello @shrielenee, @erikmarr 
Could you guys check my PR for this issue? I have added fresh screenshots from OpenOffice.
Thank you.

**Comment by AndreyChorniy** [comment]
@magento I am working on this

**Comment by shrielenee** [comment]
Yes @chiranjeevi-cj @AndreyChorniy we should remove the screenshots and discuss/explain the structure without them (they are hard to maintain, could change, etc.)

**Comment by AndreyChorniy** [comment]
Hello @shrielenee, I have updated my PR with new changes.
