### ISSUE TITLE
Set the Date Range for Each Product - Correction

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#5]
# Background

From Devdocs slack channel:

Syed Jamaluddin [4:24 PM]
@here hello team, we need to fix the information on this page https://docs.magento.com/m2/ee/user_guide/cms/widget-new-products-list.html
"Set the Date Range for Each Product" is not applicable on 2.1.x and 2.2.x and so on
Set Product as New settings can be configured only in scheduled updates. Thanks.

## Affected Docs

https://docs.magento.com/m2/ee/user_guide/cms/widget-new-products-list.html

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

# Proposed Solution

In the topic source file (src/cms/widget-new-products-list.md): 

Change the "Step 1: Set the Date Range for Each Product" section to "Step 1: Set Each Product as New" and change the task to reflect the simple toggle switch for flagging a product as new. 

Add a Note at the beginning of this Step/section to indicate that the "Set Product as New" date range setting can be configured only in scheduled updates and add a link to the "Scheduling an Update" page (cms/content-staging-scheduled-update.md).

**Comment by leslietilling** [comment]
Still a problem in Staging build :( . Will see what I can do.

**Comment by leslietilling** [comment]
This was accidentally closed from comments in an unrelated PR.

**Comment by dineshvb** [comment]
@magento I am working on this
