### ISSUE TITLE
Clarify statement about inability to add or update stock using import-export

### ISSUE THREAD

**Issue by Parrotdise** [magento/merchdocs#500]
Why does it state "You cannot add or update stocks using import-export features."?
https://docs.magento.com/m2/ee/user_guide/catalog/inventory-import-export.html

**Comment by okorshenko** [comment]
@magento I am working on it

**Comment by coderimus** [comment]
@magento I am working on it

**Comment by shrielenee** [comment]
@okorshenko @coderimus Did you mean to comment on this PR? ❓

**Comment by okorshenko** [comment]
Hi @shrielenee we tested m2-assistant bot logic

**Comment by dobooth** [comment]
Grooming team feels this is a confusing paragraph and could use clarification.
