### ISSUE TITLE
Clarify where multisite installation is available

### ISSUE THREAD

**Issue by yuxel** [magento/merchdocs#511]
"multisite installation" options are not visible in community edition

Affected page: /system/permissions-user-roles.html

**Comment by erikmarr** [comment]
@leslietilling after we unify the user guide we might need to some conditional text to this section.

**Comment by ccondra** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by ccondra** [comment]
@magento give me 2.4-develop instance with edition ee mode developer

**Comment by ccondra** [comment]
This is OK as is. The note is simply saying that if you are setting a role for a multisite installation, make sure to select the website and store where the role applies.
