### ISSUE TITLE
Feedback on page: /sales/order-status-workflow.html

### ISSUE THREAD

**Issue by sparrowek** [magento/merchdocs#52]
What blue color represent?
Is it the order state? If so then there is no Refunded state on this page - https://docs.magento.com/m2/ce/user_guide/sales/order-status-custom.html

**Comment by hickskenh** [comment]
@sparrowek Can you provide more information about your issue?

**Comment by hickskenh** [comment]
@sparrowek We haven't heard back with any additional information.  If we don't have back by Tuesday 11/25, we'll close this issue.
