### ISSUE TITLE
Broken link to General topic template in Writing Content page

### ISSUE THREAD

**Issue by vgiurgiu** [magento/merchdocs#534]
# Bug report

Broken link to **General topic template** in Writing Content page

## Description

The link to a general topic template is broken here: https://github.com/magento/merchdocs/wiki/Writing-Content#template

### Steps to reproduce

1. Navigate to the link above
2. Click the General topic template link
3. You are seeing the GitHub 404 page  

## Expected result

Expected result is to see the template.

**Comment by dobooth** [comment]
Fixed.

**Comment by vgiurgiu** [comment]
Thanks, @dobooth
