### ISSUE TITLE
Feedback on page: /catalog/catalog-menu.html

### ISSUE THREAD

**Issue by bbbyjn** [magento/merchdocs#541]
![Image 2020-06-10 at 12 42 07 PM](https://user-images.githubusercontent.com/50717406/84311223-ccfdbd00-ab17-11ea-9788-137f7a2f604f.jpg)
Doesn't match real world.
![Image 2020-06-10 at 12 42 46 PM](https://user-images.githubusercontent.com/50717406/84311289-e43caa80-ab17-11ea-8696-3a234edc04a0.jpg)

**Comment by dobooth** [comment]
Seems this is a disconnect between your version and the screenshots in the docs. This is not a docs issue. Let us know if this is not correct.
