### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by syedzaidi-magento** [magento/merchdocs#546]
This page dose not found.
https://docs.magento.com/marketplace/user_guide/extensions/shared-package-submit.html

**Comment by harshal-shah-magento** [comment]
It is a very common error that shows in Magento when you install a new extension with system.xml configuration. When you go to the System > Configuration > Extension tab, a 404 error is shown. You need to flush Magento cache Admin > System > Cache management > Flush Magento Cache, then log out and log in again and then it will be okay.

Join Magento Developers here and find more about magic brought by **[Magento Extensions.](https://www.elsner.com/magento-extension/)**

**Comment by leslietilling** [comment]
The marketplace developer/seller documentation now resides at: https://devdocs.magento.com/marketplace/sellers/getting-started.html
