### ISSUE TITLE
Clarify what "persistant shopping cart" means

### ISSUE THREAD

**Issue by brianpittvps** [magento/merchdocs#549]
This is just one example of the overall issue that the features, themselves, are not explained.  In this particular case, it's not clear what a "persistent shopping cart" even is.  There should be a blurb at the top of each setting page to say what this feature does, how it is used, why you may use it, etc.  You have done a pretty good job explaining the individual settings, but unless the user knows what the feature does, knowing which one turns it on/off isn't very helpful.

https://docs.magento.com/user-guide/configuration/customers/persistent-shopping-cart.html

**Comment by AndreyChorniy** [comment]
@magento I am working on this
