### ISSUE TITLE
Feedback on page: /sales-channels/amazon/new-third-party-listings.html

### ISSUE THREAD

**Issue by Shubham-Webkul** [magento/merchdocs#550]
I am unable to fetch Amazon product listing.

**Comment by erikmarr** [comment]
@Shubham-Webkul can you please provide more details to help us determine if this is a documentation issue or a technical issue?

**Comment by shrielenee** [comment]
We have had no response from you for over three weeks. If this issue is still relevant, please create another issue! I will be closing this now.
