### ISSUE TITLE
Clarify behavior of enabled backorders regarding Notify for Quantity Below

### ISSUE THREAD

**Issue by seansan** [magento/merchdocs#560]
This part is not clear?

`Notify for Quantity Below
The Notify for Quantity Below configuration option is configurable at the global, source, and product levels. It sends an email notification when a product’s quantity reaches a low quantity. For this example, the notification sends when the product has a quantity of 10 or less. When backorders are enabled, the Notify for Quantity Below is not deducted from the Salable Quantity.`

https://docs.magento.com/user-guide/catalog/inventory-backorders.html

**Comment by shrielenee** [comment]
Hello @seansan -- What part is not clear in the documentation you cited? Thanks!

**Comment by seansan** [comment]
no idea what this part means: When backorders are enabled, the Notify for Quantity Below is not deducted from the Salable Quantity.

**Comment by sathiyaaa** [comment]
@magento I am working on this

**Comment by seansan** [comment]
whats the fix?
