### ISSUE TITLE
Add clarification about what happens if the batch size is not reached in Inventory topic

### ISSUE THREAD

**Issue by seansan** [magento/merchdocs#561]
What happens if the batch size is not reached?

Bathc size 100

Product updated = 5

What happens then? Nothing?

https://docs.magento.com/user-guide/configuration/catalog/inventory.html

`Determines if you run bulk operations asynchronously for mass product actions including bulk assign sources, unassign sources, and transfer inventory to source. It collects bulk actions up to the Asynchronous batch size, then runs those actions. This feature is disabled by default. We recommend reviewing your performance with bulk actions before enabling. Options:
Yes - Runs all bulk operations for Inventory Management asynchronously. To enable, you must configure an asynchronous queue manager.
No - Default. Does not run bulk operations asynchronously.`

**Comment by leslietilling** [comment]
"Ready for development" means it is groomed. Inventory Management content is already moved to Experience League. Plus there seems to be no traction for anyone to provide an answer on this. Perhaps the #msi Community Slack channel can provide the the answer.

**Comment by leslietilling** [comment]
Posted question to MSI community Slack channel.

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/config/catalog/inventory.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
