### ISSUE TITLE
Update the Managing Subscribers page

### ISSUE THREAD

**Issue by jamieolney** [magento/merchdocs#571]
How do I mass unsubscribe customers? I have a list of thousands, and was wondering the best way to do this.

**Comment by ccondra** [comment]
This relates to the [Managing Subscribers](https://docs.magento.com/user-guide/marketing/newsletter-subscribers.html) page.  Under Cancel a Subscription, we should add an instruction to select the checkbox of each subscriber that you want to cancel.

**Comment by leslietilling** [comment]
There is currently a PR for 2.40 docs where this functionality was updated for the release (https://github.com/magento/merchdocs/pull/589). 

This issue should address 2.3.x docs and review 2.4.0 after GA for any changes needed there.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
