### ISSUE TITLE
Feedback on page: /cms/page-hierarchy-node-add.html

### ISSUE THREAD

**Issue by apoltoratskyi** [magento/merchdocs#583]
Misprint in section 5:  https://docs.magento.com/user-guide/cms/page-hierarchy-node-add.html#step-5-choose-the-menu-layout.
"If you want the **mode** to appear in the menu"  :  mode => node

**Comment by erikmarr** [comment]
@apoltoratskyi thanks for the feedback! This has been fixed in the documentation.
