### ISSUE TITLE
Are reward points addition only applicable with sub or grand total?

### ISSUE THREAD

**Issue by justjolly** [magento/merchdocs#586]
Deduction/Addition of reward points is only applicable with sub total or grand total ?

https://docs.magento.com/user-guide/marketing/reward-point-configure.html

**Comment by danidelcar** [comment]
@leslietilling @hickskenh can this issue be groomed so can be open to community for work?

**Comment by hickskenh** [comment]
@leslietilling @danidelcar i don't see why not.  unless leslie knows of something.

**Comment by danidelcar** [comment]
I'll defer to @leslietilling about this

**Comment by leslietilling** [comment]
This could be done if someone knows the answer to the question.

**Comment by dshevtsov** [comment]
The topic was moved to https://experienceleague.adobe.com/en/docs/commerce-admin/marketing/merchandising/reward-points/rewards-loyalty#enable-reward-point-operations-for-your-store.
If the issue is still relevant, please reopen it in https://github.com/AdobeDocs/commerce-admin.en.
