### ISSUE TITLE
Missing Authentication Locks configuration info

### ISSUE THREAD

**Issue by keharper** [magento/merchdocs#596]
# Bug report

## Description

The Stores > Configuration > Services > OAuth > Authentication Locks panel is not documented in https://docs.magento.com/user-guide/configuration/services/oauth.html

The panel was added in https://github.com/magento/magento2/pull/9820

### Steps to reproduce

Follow the path listed above

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
