### ISSUE TITLE
Google Tag Manager/ Enhance eCommerce -- Improvements needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#6]
# Background

User feedback for GTM and GEC topics:

https://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html
`There's no Account type option to be filled, either Container Id. I'm using Magento 2.3 Community`

https://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html
`Magento 2.3.0 does not include an option to choose an Account Type unser Stores-Configuration-Sales-Google Analytics.`

https://docs.magento.com/m2/ee/user_guide/marketing/google-tag-manager.html

`Step 3, logging in to . Magento 2.3 Stores>configuration>sales>google analytics only has 4 boxes to fill out/select, not as depicted in your guide`

`Not showing up on my Magento 2.3`

`My default 2.2.6 has no account type field?`

`Do a tutorial guys.`

`On step 3..4.b Could it be that it's using version 1.x fields? Because I don't have Account Type selector. Really nice docs anyways.`

`If Google tag manager is not installed in Magento then what are the steps?`

https://docs.magento.com/m2/ee/user_guide/marketing/google-enhanced-ecommerce.html

`It seems like it is not complete. There are 8 triggers, and only 7 tags, so 1 trigger is unused (Checkout Only). In step 3 there are only 6 tag completions, the tag "Checkout tracking" is missing.`

`The steps are not explain fully, its complicated to understand`

https://docs.magento.com/m2/ee/user_guide/configuration/sales/google-api.html	

`This is not what I see in my admin. I only see the settings for Google Analytics. There is no place to change the account type to tag manager.`

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

TBD

**Comment by hickskenh** [comment]
@mmansoor-magento  Hey.  when i looked at the google api topic yesterday, i found that neither topic (ee or ce) was displaying correctly. the version tags where not placed correctly. I've corrected the issue and will be merging the PR today.  the corrected documents (ce and ee versions) will be updated in the overnight build.
