### ISSUE TITLE
Product reviews - Improvements needed

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#60]
# Topic clarification/correction request

User feedback:

https://docs.magento.com/m2/ce/user_guide/marketing/product-reviews.html	
`My store is set up to accept customer reviews of products, but the review form does not include a star rating, and reviews, once enabled, are not available on the store front.`

## Possible solutions

A checklist or other way to make sure that users have everything configured to include the ratings and reviews on the storefront.

**Comment by ZhovnirMaria** [comment]
@magento I working on it

**Comment by ZhovnirMaria** [comment]
@magento I am working on this

**Comment by ZhovnirMaria** [comment]
Hi, @leslietilling 
I have updated some information on the product review. In my opinion, this topic is well described, and users should not have any problems with the ratings and reviews on the storefront. Let me know if I missed something.
Thank you!

**Comment by leslietilling** [comment]
As @ZhovnirMaria  mentioned. This is already addressed.
