### ISSUE TITLE
Update about pre-step in 2factor Auth topic (maybe revise left-hand TOC to be indicative of steps)

### ISSUE THREAD

**Issue by aamritasingh** [magento/merchdocs#618]
What is the pre-step ? to see the setting of SECURITY in left panel.

**Comment by ccondra** [comment]
I don't see any missing step, but I think we can "connect the dots" better by linking to the other topics. I recommend moving the  "Using 2FA" topic up one level in the left nav, which would make "Managing 2FA" the third topic in the section. Then at the end of each topic, link to the next for more info.  Please let us know if there's anything else. Thanks!
