### ISSUE TITLE
Custom contact page example no longer works in Magento 2.4.0

### ISSUE THREAD

**Issue by hostep** [magento/merchdocs#648]
# Bug report

## Description

This is regarding the page: https://docs.magento.com/user-guide/stores/contact-us.html#method-2-without-sample-data
The step where it says to insert `{{block class="Magento\Contact\Block\ContactForm"
 name="contactForm" template="Magento_Contact::form.phtml"}}` no longer works in Magento 2.4.0.

See https://github.com/magento/magento2/issues/29357 for more info

### Steps to reproduce

See https://github.com/magento/magento2/issues/29357

## Expected result

Instructions for custom contact page are correct

## Magento release version

- [x] 2.4.x

   Specify a patch release number, if applicable: 2.4.0

- [ ] 2.3.x

   Specify a patch release number, if applicable:

**Comment by leslietilling** [comment]
This is resolved by @mrtuvn
