### ISSUE TITLE
Clarify Cancel Order Process

### ISSUE THREAD

**Issue by kr0w94** [magento/merchdocs#651]
the process that leads an order to be "canceled" seems to be missing

**Comment by ccondra** [comment]
The information about cancelling orders is on the [Order Workflow](https://docs.magento.com/user-guide/sales/order-workflow.html) page. We need to connect the dots here, and also make it more prominent. It wouldn't hurt to have a separate topic.

**Comment by ccondra** [comment]
This issue has been addressed by PR #944
