### ISSUE TITLE
Check Developer vs Production mode on two different pages

### ISSUE THREAD

**Issue by victortodoran** [magento/merchdocs#658]
I think there is a mistake on this page. 
![image](https://user-images.githubusercontent.com/25669334/89629308-46125a00-d8a6-11ea-8ab2-888b3923f25f.png)
An on this one as well
![image](https://user-images.githubusercontent.com/25669334/89629342-5591a300-d8a6-11ea-9fa6-f6ee1b7164f5.png)

This features make **no** sense if they work only in **developer mode.** I think **production mode** is the right thing to say.

sources: 
https://docs.magento.com/user-guide/v2.3/design/merge-javascript.html
https://docs.magento.com/user-guide/v2.3/design/merge-css.html

Affected page: /design/merge-css.html

**Comment by khrystynastolbova** [comment]
@magento I am working on this

**Comment by khrystynastolbova** [comment]
On the Admin sidebar _Stores > Settings > Configuration > Advanced > Developer_ section is disabled when working in Production Mode and available in Developer and Default modes.

There are other ways to merge it in Production mode:
1. config.php  https://devdocs.magento.com/cloud/live/sens-data-initial.html#change-config
2. console https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/themes/js-bundling.html

I suggest changing the text to something like:
"JavaScript files can't be merged from the admin panel when working in Production Mode" 
or
"JavaScript files can be merged from the admin panel when working in Developer and Default Modes"
