### ISSUE TITLE
Update list of supported email clients

### ISSUE THREAD

**Issue by Dnd-ward** [magento/merchdocs#659]
Seems that the page on email-client-supported hasn't been update since 11 month.

For example, there's no informations about compatibility of M2 2.3 /2.4 with native client on iOS 8 until iOS 13. Same on Android now on v10. 

Can you please update the page ? 

![Screenshot 2020-08-07 at 18 07 48](https://user-images.githubusercontent.com/69358293/89665383-e84b3580-d8d8-11ea-96a6-fb0c3fc35b43.png)

Affected page: /marketing/email-clients-supported.html

**Comment by hickskenh** [comment]
moved to Jira [COMDOX-225](https://jira.corp.adobe.com/browse/COMDOX-225)
