### ISSUE TITLE
Page Not Found when downloading GTM_M2_Config_json.txt

### ISSUE THREAD

**Issue by lagunacellar** [magento/merchdocs#661]
# Bug report

## Description

When configuring Google Tag Manager Account, as outlined in this page:
https://docs.magento.com/user-guide/marketing/google-tag-manager.html

The linked sample json file is not found.

### Steps to reproduce

1. There is supposed to be a linked file at URL https://docs.magento.com/m2/downloads/GTM_M2_Config_json.txt
2. The link results in Page Not Found

## Expected result

Expected to retrieve linked sample file GTM_M2_Config_json.txt, instead receive error Page Not Found

## Possible solutions

Fix the dead link.

## Magento release version

- [X] 2.4.x

   Specify a patch release number, if applicable:

- [X] 2.3.x

   Specify a patch release number, if applicable:

## Additional information

None

**Comment by hiroshi-dewa** [comment]
I had the same problem.

And, the characters in the text link are incorrect.
incorrect: `GMT_M2_Config_json.txt`
correct: `GTM_M2_Config_json.txt`

**Comment by leslietilling** [comment]
The "Page not found" was due to the m2/downloads directory being removed during our changeover and removal of 2.2 docs. All of these download files are now restored, but will soon be relocated to downloads/m2 in keeping will our newer URL patterning.
