### ISSUE TITLE
Feedback on page: /tax/vertex.html

### ISSUE THREAD

**Issue by CalzaFino** [magento/merchdocs#67]
I am tryng to update to Magento 2.3.3 and I get this error when i run compilation:

Fatal error: Interface 'Vertex\Tax\Model\Flexfield\Processor\TaxCalculationFlexFieldProcessorInterface' not found in /srv/public_html/vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php on line 24

The module is disabled and it is still preventing compilation from runnig.
How can I solve this problem?

**Comment by hellotaran** [comment]
This should not be here as this Magento repo is for Merchant Docs. This issue needs to be open on magento/magento2 repo.

**Comment by hickskenh** [comment]
@CalzaFino Thank you for your submission. I agree with @hellotaran.  Please open an issue to help determine your software update issue.  If you think the documentation topic needs an update or additional information after your issue is resolved, please reopen an issue in the merchdocs repo.
