### ISSUE TITLE
Flat catalog - link to KB

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#69]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html

## Description

For those who choose to continue with the use of the flat catalog (it is not recommended), disabling the flat tables and indexers. The Support site has a published article to provide details about disabling this on the server side.

https://support.magento.com/hc/en-us/articles/360034631192

## Possible solutions

Add information to the topic about this solution for the issue of slow performance of the flat catalog and the link. Also add a note that the solution will require developer assistance.

**Comment by hickskenh** [comment]
this issue was fixed and merged in PR #98

**Comment by atwixfirster** [comment]
@leslietilling , could you please remove `ready for dev` label from this issue because PR already created for it.

Thank you!
