### ISSUE TITLE
Tiered Pricing - Improvements needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#7]
# Background

User feedback for pricing topics:

https://docs.magento.com/m2/ce/user_guide/catalog/pricing-advanced.html
`You haven't described how special pricing interacts with Tired pricing.(I think they mean "tiered".)`

https://docs.magento.com/m2/ce/user_guide/catalog/product-price-tier.html
`This does not address the bulk/tier pricing on other parts of the site. For instance, I need to show the discount a customer is getting from the bulk/tier pricing on the cart AND checkout. How do I do this??`

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

TBD

**Comment by dobooth** [comment]
Close as fixed.
