### ISSUE TITLE
'Use deferred Stock update' - field needs documentation

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#70]
# Topic clarification/correction request

Magento customer inquiry:

> what does `Use deferred Stock update` in 2.3 do - I can't find it in the user guide
> https://docs.magento.com/m2/b2b/user_guide/configuration/catalog/inventory.html 

## Topic Link

https://docs.magento.com/m2/b2b/user_guide/configuration/catalog/inventory.html 

## Description

This field appears only under the following circumstances

EE or EE/B2B is installed
The Store > Configuration > Catalog > Inventory > Product Stock Options > Back orders is set to anything besides the default value "No backorders"

This ScalableInventory module apparently defines this functionality. (Not MSI, but MSI might deprecate this functionality now). I think it's been around since at least 2.1

## Possible solutions

Document this field

**Comment by dineshvb** [comment]
@magento I am working on this
