### ISSUE TITLE
Feedback on page: /catalog/settings-advanced-cross-sells.html

### ISSUE THREAD

**Issue by cschan2000** [magento/merchdocs#709]
Cross Sell Product

**Comment by ccondra** [comment]
After two weeks without a response, we are closing this pull request because it doesn't meet our [Contributor Guidelines](https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md).  Thank you.

**Comment by ccondra** [comment]
After two weeks without a response, we are closing this pull request because it doesn't meet our [Contributor Guidelines](https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md).  Thank you.
