### ISSUE TITLE
Image import - must use hardcoded directory

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#71]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ce/user_guide/system/data-import-product-images.html

## Description
Starting from 2.3.2-p2/2.3.3 merchants must use one specific “hardcoded” directory for images import.

The topic states the following:

`You can use a different folder on the Magento server, as long as the path to the folder is specified during the import process.`

But this results in an error:

`Imported resource (image) could not be downloaded from external resource due to timeout or access permissions in row(s)`

## Possible solutions

Update this topic to tell users that they cannot use another image file directory and import only works for the hard-coded path.

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/merchdocs/pull/103

This is a feature of Magento `2.3.3`/`2.3.2-p2`/`2.3.3` versions. In the mentioned releases a root folder for images is 

```
<Magento root folder>/var/import/images
```

Value which admin sets in the **Images File Directory** field is concatenating to `<Magento root folder>/var/import/images` folder.

For example, admin sets `/pub/media/import` in  the **Images File Directory** field. So, Magento will try to import files from the 
```
<Magento root folder>/var/import/images/pub/media/import
```
directory.

**Comment by atwixfirster** [comment]
I've created a PR to core with better explanations for **Images File Directory** option.

https://github.com/magento/magento2/pull/25248
