### ISSUE TITLE
Feedback on page: /marketing/product-compare.html

### ISSUE THREAD

**Issue by cschan2000** [magento/merchdocs#710]
Compared products

**Comment by erikmarr** [comment]
Hi @cschan2000 can you provide more context regarding this issue? It's not clear to me what needs to change in this topic. Same with all the other issues you recently reported:
https://github.com/magento/merchdocs/projects/4

**Comment by ccondra** [comment]
After two weeks without a response, we are closing this pull request because it doesn't meet our [Contributor Guidelines](https://github.com/magento/merchdocs/blob/master/.github/CONTRIBUTING.md).  Thank you.
