### ISSUE TITLE
Feedback on page: /magento/magento-extensions.html

### ISSUE THREAD

**Issue by d-consulting** [magento/merchdocs#716]
Hello everyone!
Here my question: I'm going to install Magento 2.4 via Installatron.
I'm going to have a complete (containing also sample data) isnstallation.
When installing Magento 2.3.5 it came with about 20 modules and about 20 extensions preinstalled.
Can someone tell me Magento 2.4 version what modules and extensions come with a new installation via Installatron?
really thanks!

**Comment by d-consulting** [comment]
@magento I am working on this

**Comment by d-consulting** [comment]
@magento add to contributors team

**Comment by ccondra** [comment]
Hi there -- As a third-party service, and you will have to contact the Installatron support team for answers to your questions about the specific modules and extensions included in their custom installation of Magento.

To learn more about our 2.4 release,  see the [2.4 Release Information](http://devdocs.magento.com/guides/v2.4/release-notes/bk-release-notes.html).  I hope this helps!
