### ISSUE TITLE
Feedback on page: /cms/page-builder-templates.html

### ISSUE THREAD

**Issue by WMercer** [magento/merchdocs#717]
I cannot see the Templates block in the Content sidebar. Is there any place I can set up it? I personally suggest that this page, for explaining the template usage, can be considered talking about the gate of such function at first.
version Magento 2.3.4 EE
![image](https://user-images.githubusercontent.com/55430119/91708967-ab5f1f80-ebb4-11ea-8f70-9f96b80cd8cc.png)

**Comment by bdenham** [comment]
Hey @WMercer, the Page Builder template feature was introduced in Page Builder 1.3.0 for Magento Commerce 2.3.5. So you will not see it in your Magento Commerce version 2.3.4. See Page Builder Release Notes here: https://devdocs.magento.com/page-builder/docs/release-notes.html#130-for-magento-commerce-235. 

I will close this issue for now. Please let me know if you would like to reopen the issue for additional feedback.
