### ISSUE TITLE
Feedback on page: /stores/security-google-recaptcha.html

### ISSUE THREAD

**Issue by scholtz** [magento/merchdocs#72]
Hi,

there is no security tab in clean magento open source 2.3.3 installation.

![magento-no-security](https://user-images.githubusercontent.com/1223439/66712671-54840800-eda0-11e9-86af-5c35e224e5d8.png)

**Comment by scholtz** [comment]
I also started the discussion on forum: https://community.magento.com/t5/Magento-2-x-Admin-Configuration/reCaptcha/m-p/144642

**Comment by hickskenh** [comment]
@scholtz Thanks for the heads up.  This does not look like a docs issue.  your configuration screen shot is missing additional tabs that should be there.  I'm going to ask around and see who would be a contact for you.  based on all of my environments here, docs are correct.

**Comment by igrybkov** [comment]
@scholtz, I've just tried to reproduce the issue and I see the tab on fresh installation. That's how I've created Magento instance: `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition:2.3.3`
<img width="1549" alt="Screenshot 2019-10-25 14 00 58" src="https://user-images.githubusercontent.com/228986/67597221-3c14d580-f730-11e9-8cff-7b96fbccb898.png">

**Comment by hickskenh** [comment]
@scholtz Thank you for your feedback! Your issue doesn't seem to be related to Magento documentation. I was going to point you to [Stack Exchange](https://community.magento.com/) for help, but it looks like you've done that.  Another option would be to open a [Support ticket](https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#support-tickets).  With the engineer's confirmation, I'm closing this doc request.
--
