### ISSUE TITLE
Remove outdated links

### ISSUE THREAD

**Issue by keharper** [magento/merchdocs#721]
On https://docs.magento.com/user-guide/system/tools.html, the links from "modules" and "extensions" at the bottom of the page are invalid. Remove the "as well as modules and extensions." clause from the sentence.

This issue was originally reported in https://github.com/magento/devdocs/issues/7787, but that was the wrong repo.

**Comment by sudhanshu-bajaj** [comment]
PR is ready to review [link](https://github.com/magento/merchdocs/pull/747).

**Comment by sudhanshu-bajaj** [comment]
Already fixed [here](https://github.com/magento/merchdocs/pull/747). Please close the issue.

**Comment by leslietilling** [comment]
fixed in referenced PR
