### ISSUE TITLE
Feedback on page: /stores/security-two-factor-authentication.html

### ISSUE THREAD

**Issue by vkranjith** [magento/merchdocs#729]
In the Magento Release 2.4.0 I was trying to figure out a way to disable the 2FA in my dev environments and was unable to follow this documentation to find it. I see this option in the older Magento 2.3.x version but not in the 2.4.0.

Can this be corrected with the appropriate screenshot?

I would like that enable/disable feature to be available in a dev environment as it's difficult to setup 2FA as it keeps throwing error regarding not able to send an email on dev servers.

<img width="946" alt="2FA Authentication Configuration" src="https://user-images.githubusercontent.com/8416538/92561723-5bf2b080-f292-11ea-9534-a36b972bb263.png">

**Comment by vkranjith** [comment]
@magento I am working on this

**Comment by irenelagno** [comment]
@magento give me 2.4-develop instance

**Comment by shrielenee** [comment]
Because the related PR https://github.com/magento/merchdocs/pull/735 was merged without the trigger phrase, this issue was not closed. Manually closing.
