### ISSUE TITLE
Test instance deployer

### ISSUE THREAD

**Issue by leslietilling** [magento/merchdocs#736]
# Topic clarification/correction request

## Topic Link

N/A

## Description

Need an issue to deploy an instance for these updates.

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable: 2.4.1

- [ ] 2.3.x

   Specify a patch release number, if applicable:

## Possible solutions

Research needed

**Comment by leslietilling** [comment]
@magento give me 2.4.1 instance with ee

**Comment by jeff-matthews** [comment]
@leslietilling, I think this failed because we don't yet have a 2.4.1 tag in the magento2 repo.

**Comment by leslietilling** [comment]
@magento give me 2.4.1-develop instance with edition ee

**Comment by leslietilling** [comment]
@jeff-matthews  I reached out to Iryna and she says they don’t have a solution right now but she will bring this to team to see what they can do to accommodate this.

**Comment by leslietilling** [comment]
@magento give me 2.3.5 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4.0 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4.1 instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4.1-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.3.5 instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.3.6 instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.3-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.3-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.3-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.3-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.3.7-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.3 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.3-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4.3 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4.4 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4.4 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@maagento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by dobooth** [comment]
@magento give me 2.4-develop instance

**Comment by dobooth** [comment]
https://github.com/magento give me 2.4-develop instance

**Comment by dobooth** [comment]
@magento give me 2.4-develop instance

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by dobooth** [comment]
https://github.com/magento give me 2.4-develop instance with edition ee

**Comment by dobooth** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by dobooth** [comment]
@magento give me 2.4-develop instance

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by dobooth** [comment]
@magento give me 2.3.7  instance

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by dobooth** [comment]
https://github.com/magento give me 2.4-develop instance with edition ee

**Comment by dobooth** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@mageneto give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4.6 instance with edition b2b

**Comment by leslietilling** [comment]
@magento give me 2.4.6 instance with edition ce

**Comment by leslietilling** [comment]
@magento give me 2.4.6 instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4.6 instance with edition ce

**Comment by leslietilling** [comment]
https://github.com/magento give me 2.4-develop instance with edition ee

**Comment by leslietilling** [comment]
@magento give me 2.4-develop instance with edition ee
