### ISSUE TITLE
Stored payment methods are available in Open Source

### ISSUE THREAD

**Issue by keharper** [magento/merchdocs#749]
Affected topic: /customers/account-dashboard-stored-payment-methods.html
Releases: 2.3 and 2.4

The caption to the image of the page indicates that stored payment methods are a Commerce feature. This is actually a feature in Open Source.

**Comment by ccondra** [comment]
To avoid confusions, the "ee only" tag should be removed from the image caption.  (The screenshot just happens to have been taken from a Magento Commerce instance.)

**Comment by ccondra** [comment]
This was fixed in PR #930
