### ISSUE TITLE
Scheduling an Export

### ISSUE THREAD

**Issue by magentogreek** [magento/merchdocs#766]
# New topic request

## Magento release version

- [ ] 2.4.x

   Specify a patch release number, if applicable:

- [x] 2.3.x

   Specify a patch release number, if applicable:

## Content checklist

- [ ] The topic provides an explanation of how ____ works.
- [ ] The topic provides steps for ____.
- [ ] The topic contains examples that shows ____.
- [ ] The tutorial should walk-through a complicated process.
- [ ] Other (please specify)

**Comment by magentogreek** [comment]
the option of Scheduling an Export my magento 2.3.2 is not showing, how to enable this option in magento

**Comment by dobooth** [comment]
Hi @magentogreek , Thanks for the issue. Please fill out the description so we know what the issue is. The Export feature is Magento Commerce only, so if are on Community Edition, you will not see it. Please clarify so we can see if this topic needs an update. Thanks.

**Comment by keharper** [comment]
@magentogreek Are you running Magento Open Source?

**Comment by ccondra** [comment]
I believe that you're probably using Magento Open Source, which doesn't support export scheduling. We haven't heard back from you, so I'm closing the issue for now. Thank you.
