### ISSUE TITLE
Provide a better explanation of what "execution time" means on this page

### ISSUE THREAD

**Issue by adamlavery** [magento/merchdocs#775]
Feedback on page: /system/data-import-history.html

Please explain execution time. Is that the time it took to execute (elapsed time) or the time it was actually executed (absolute time)? 

I hope it's not the former because that would mean importing 27 customers took 23:59!

**Comment by keharper** [comment]
@adamlavery I'm not sure what you're asking. The screenshot shows a bit over 5 hours. Execution would mean the time the process took to run.

**Comment by adamlavery** [comment]
Ok, so that's what I mean here. Nothing to explain what execution time means - it's ambiguous. Needs clarifying that this is the time taken to execute, not the time it was executed. In any case, what's given is wrong: see this from our site:

![image](https://user-images.githubusercontent.com/13659750/94900404-d3c88b00-048c-11eb-8623-5647db9d019a.png)

This was what was showing at the time this ticket was raised. Clearly it cannot have executed for 23:59:41 an hour after it was submitted! Something is seriously wrong if it takes 24hrs to process 27 customer record updates! Hence the confusion on what execution time was showing. But that's an issue for the rather poorly considered changes to importing than the docs.
