### ISSUE TITLE
Page /system/data-export.html needs to be updated

### ISSUE THREAD

**Issue by katmoon** [magento/merchdocs#782]
The exported file is no longer automatically exported " in the download location for your web browser". It's processed through a message queue https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html
Cron job should be running for the file to be exported. The file is also saved to var/export/ folder.

![image](https://user-images.githubusercontent.com/1260101/94863059-79cdb400-03ff-11eb-95b5-290d10098f81.png)

Please update the user guide to better describe the expected behavior.

**Comment by sathiyaaa** [comment]
@magento I am working on this
