### ISSUE TITLE
Feedback on page: /cms/widget-new-products-list.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#785]
The Set Product as New **From** and **To** date fields are not applicable to Magento Commerce - those are solely in the domain of Open Source.
![image](https://user-images.githubusercontent.com/68703716/95400569-be55c580-08bf-11eb-9652-353610328f64.png)

They must create a Scheduled Update to specify the Start and End dates during which the product is to be shown as New:  https://docs.magento.com/user-guide/cms/content-staging-scheduled-update.html

Please link to the above article and attach the Magento Commerce key to it.

**Comment by erikmarr** [comment]
Thanks for your feedback @ak77-prime!
