### ISSUE TITLE
Feedback on page: /system/data-import-product-images.html

### ISSUE THREAD

**Issue by VidhyaKumar** [magento/merchdocs#79]
![Screen Shot 2019-10-16 at 11 40 47 am](https://user-images.githubusercontent.com/1960813/66886427-da56bc00-f009-11e9-84e8-9ada18f0187c.png)

Shouldn't product image import directory be <Magento installation>/var/import/images ?

Magento version 2.3.3

**Comment by leslietilling** [comment]
This was fixed in https://github.com/magento/merchdocs/pull/103
