### ISSUE TITLE
Product Compare - Improvements Needed

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#8]
# Background

User feedback for product compare topics:

https://docs.magento.com/m2/ce/user_guide/marketing/product-compare.html
`Doesn't have any useful details on how the notice works.`

https://docs.magento.com/m2/ce/user_guide/marketing/products-viewed-compared.html 
`This section doesn't include most of the new options included in Magento 2.3, meaning it's not as useful as I'd like.`

https://docs.magento.com/m2/ee/user_guide/marketing/product-compare.html
`Needs to include how to hide the module. This should be a basic function that should be put in the backend, along with hiding the customer login, reviews etc.`

## Affected Guides

- [x] Open Source
- [x] Commerce
- [x] B2B

## Possible solutions

Address the listed pages and the feedback. A working example of the product comparison feature would be very helpful here.

As an additional item (worth special achievement points),  a "start-to-finish" type of tutorial to get product comparisons implemented would be a great.

**Comment by leslietilling** [comment]
Old comments from Hotjar. Closing as N/A for current docs.
