### ISSUE TITLE
Vat statement incorrect in /tax/vat.html

### ISSUE THREAD

**Issue by antonioglass** [magento/merchdocs#804]
The following statement is wrong “No VAT is charged if the merchant and customer are located in different EU countries”. The right statement will be “No VAT is charged if the merchant and customer are located in different EU countries, and customer is a legal entity (company) with a valid VAT number”. If customer is a private person, VAT must be charged.

**Comment by shrielenee** [comment]
@leslietilling @ccondra Do we have the most up-to-date info on VAT?

**Comment by ccondra** [comment]
We're investigating this.

**Comment by leslietilling** [comment]
After reaching out to our Product Management.....

According to the Magento VAT ID validation, it works in the following manner for these scenarios:

1. After customer saves or add default billing address with valid VAT Number and same country as store country then customer group defined under “Group for Valid VAT ID - Domestic” will be assigned to the customer. The following message will be displayed: `Your VAT ID was successfully validated. You will be charged tax.`

2. After customer saves or add default billing address with valid VAT Number and country within EU that differs from store country then customer group defined under “Group for Valid VAT ID - Intra-Union” will be assigned to the customer. The following message will be displayed: `Your VAT ID was successfully validated. You will not be charged tax.

So, it actually depends on a valid VAT number of the customer, if it is not provided then VAT is still charged even if address is in different country.

We will update this topic accordingly.

**Comment by gwharton** [comment]
VAT should be charged based on where the item is being sent, not where the entity buying the item is based.

An NL business for example, buying a product from a UK store for delivery to a UK address, would have to pay UK VAT and would not be entitled to Zero Rate Intra EU supply.

The default setting of VAT Calculation Based on "Shipping Address" is the correct default and appropriate in most scenareos.

For a VAT registered business in one EU country supplying goods to a private individual in another EU country, then VAT MUST be charged at the appropriate rate according to the source country. This is classed as a "Distance Sale".

For a VAT registered business in one EU country supplying goods to a VAT registered business in another EU country, then the supplier MAY (but doesn't have to) Zero Rate the supply in accordance with Article 138 Directive 2006/112/EC. This is an "Intra EU Zero Rated supply of goods". The supply should only be Zero Rated if certain conditions are met by the seller, e.g obtaining proof that they checked the VAT number is valid, and they have proof of export within a certain timeframe.

In the second case, If the supply is not Zero Rated by the seller, then VAT charged at the appropriate rate according to the source country would be charged, and this can be claimed back by the receiving country from their local TAX office.

It is extremely difficult to summarise EU VAT in a single sentence.

@leslietilling Whether the VAT validation uses the billing or shipping address should be determined by the setting "VAT Calculation Based On" and not hard coded to the Billing Address, but I guess thats another issue altogether.

**Comment by ccondra** [comment]
We should also recommend that people consider using Vertex Cloud if they need additional tax management capabilities. Vertex falls back to the VAT ID in the customer account if another isn't specified during checkout. This handles the scenario where a customer ships to a different address.

**Comment by ccondra** [comment]
This update is complete. Thanks for your help!  
See: https://github.com/magento-commerce/merchdocs/pull/366
