### ISSUE TITLE
Tax Rounding Errors, Calculation settings tables, multiple issues.

### ISSUE THREAD

**Issue by gwharton** [magento/merchdocs#819]
https://docs.magento.com/user-guide/tax/warning-messages.html

The heading "Tax calculation method based on: excluding tax" actually read "Catalog Prices : excluding tax"

Update : See comment https://github.com/magento/merchdocs/issues/819#issuecomment-715180059 for detailed description.

**Comment by ps9793** [comment]
@gwharton Can I be assigned to this issue ?

Also, you want the heading "Tax calculation method based on: excluding tax" changed to "Catalog Prices : excluding tax" to match the headings on the page.
Am I correct in my understanding here ?

**Comment by gwharton** [comment]
Actually, on further inspection, there are a number of problems with the tables on this page.

### Problem 1

The page has two sections containing tables

1. https://docs.magento.com/user-guide/tax/warning-messages.html#tax-calculation-method-based-on-excluding-tax
2. https://docs.magento.com/user-guide/tax/warning-messages.html#catalog-prices-including-tax

I beleive these two tables should have the headings

1. Catalog prices: excluding tax
2. Catalog prices: including tax

Someone will need to confirm that this is the case, as I am no authority on this, but the tables as they are make no sense.

### Problem 2

Presumably the table headings down the left hand side show the setting `Sales -> Tax -> Price Display Settings -> Display Product Prices In Catalog` and the headings across the top of the tables show the setting `Sales -> Tax -> Calculation Settings -> Tax Calculation Method Based On`. The first table shows settings when `Sales -> Tax -> Calculation Settings -> Catalog Prices` is set to Excluding Tax and the second table shows settings when `Sales -> Tax -> Calculation Settings -> Catalog Prices` is set to Including Tax. This is not clear from looking at the tables.

### Problem 3

Why is there the line in the top table, "Tax Class for Shipping". That doesn't make any sense being there does it? It doesn't affect any results read from the table in any way!

### Problem 4

All of this in addition, there is bug https://github.com/magento/magento2/issues/30591 which reports that the actual checks in the software to determine whether the combination of settings results in rounding errors does not match the data in the table.

Really, a Magento_Tax person should really take a look at this and confirm the correct course of action to both this issue and also  https://github.com/magento/magento2/issues/30591

**Comment by chiranjeevi-cj** [comment]
@magento Iam working on this.

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
@dobooth Can you please elaborate on the things to be changed?
