### ISSUE TITLE
Update "Creating Categories" for Adobe Stock Integration

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#83]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/catalog/category-create.html
From: `src/catalog/category-create.md`

## Description

- [ ] Revise the "Complete the Category Content" section to account for Adobe Stock Integration
- [ ] Add any link for Stock integration information

## Additional information

This should be assigned to the [Adobe Stock Integration Docs Project](https://github.com/magento/merchdocs/projects/6) and stems from #77. I am happy to take this one.

**Comment by bdenham** [comment]
Hey @filmaj, I'm assuming this is no longer an issue. It looks like you closed the corresponding PR #188. Closing.
