### ISSUE TITLE
Feedback on page: /marketing/price-rules-cart-create.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/merchdocs#836]
[2.3]
Under Fields Description > Rule Information > Coupon, it contains the To and From fields at the bottom of the table - these fields are not present in Magento Commerce.

Also, the caption of the image in Step 4 of https://docs.magento.com/user-guide/v2.3/marketing/price-rules-cart-create.html#step-1-add-a-new-rule mentions Coupon Settings - recommend changing it to **Manage Coupon Codes** as well

**Comment by dobooth** [comment]
Thanks for the issues, @ak77-prime. I took care of the Manage Coupon Codes issue. For the To: and From: fields, there is a badge next to them that specifies that those fields are Open Source only.
