### ISSUE TITLE
New topic for "Using Adobe Stock Images"

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#85]
# New topic request

## Description

The topic provides an explanation of how image management in the Media Gallery works when combined with the Adobe Stock Integration extension. It should include an overview of:

- the Adobe Stock UI
- how signing in to Adobe Stock works
- how asset finding works between the Media Gallery as well as the Adobe Stock Integration
- how images can be saved from Adobe Stock into Magento's Media Gallery
- how licensing images work with Adobe Stock

## Content checklist

- [ ] Create new .md file in src/catalog directory: adobe-stock-manage.md
- [ ] Topic title: "Using Adobe Stock Images"
- Topic contents:
    - [ ] Overview of the Adobe Stock UI as displayed in Magento (do not use numbered or lettered callouts as in the AEM docs)
    - [ ] "Account sign in" section
    - [ ] "Find assets" section
    - [ ] "Add to Media Gallery" section
    - [ ] "License assets"  section
- Add link to html output ("Images and Video" section) in .yml files:
    - [ ] `src/_data/ce/catalog.yml` -- add link as child of "Adding Product Images"
    - [ ] `src/_data/ee/catalog.yml` -- add link as child of "Adding Product Images"
    - [ ] `src/_data/b2b/catalog.yml` -- add link as child of "Adding Product Images"

## Additional information/resources

This should be assigned to the [Adobe Stock Integration Docs Project](https://github.com/magento/merchdocs/projects/6) and stems from #77. I am happy to take this one.

**Comment by filmaj** [comment]
I bundled this content together in #187

**Comment by bdenham** [comment]
Fixed by #187.
