### ISSUE TITLE
Inactivated gift registries can't really be re-activated

### ISSUE THREAD

**Issue by keharper** [magento/merchdocs#857]
Affected page: https://docs.magento.com/user-guide/marketing/gift-registry-information.html

The docs should mention that when a gift registry is made inactivate, the registry can't be searched or linked to. Also, if you re-activate the registry, links remain broken. That might be a bug, but that's how it is today.

Also, the caption under the first graphic states this is a B2B feature. It's really a EE feature.

**Comment by dineshvb** [comment]
@magento I am working on this
