### ISSUE TITLE
Update "Inserting an Image" for Adobe Stock Integration

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#86]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/cms/editor-insert-image.html
From: `src/cms/editor-insert-image.md`

## Description

- [ ] Modify beginning paragraph to reflect both type of image additions
- [ ] Update procedures and screens to reflect changes to the UI

## Additional information

This should be assigned to the [Adobe Stock Integration Docs Project](https://github.com/magento/merchdocs/projects/6) and stems from #77. I am happy to take this one.

**Comment by bdenham** [comment]
Fixed by #190. Closed.
