### ISSUE TITLE
Update "Media Storage" for Adobe Stock Integration

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#87]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/cms/media-storage.html
From: `src/cms/media-storage.md`

## Description

- [ ] Update overview to describe manual upload vs. Adobe Stock
- [x] Update procedures and screens to reflect changes to the UI

## Additional information

This should be assigned to the [Adobe Stock Integration Docs Project](https://github.com/magento/merchdocs/projects/6) and stems from #77. I am happy to take this one.

**Comment by bdenham** [comment]
Fixed by #191. Closing.
