### ISSUE TITLE
Update "Image" (Page Builder) for Adobe Stock Integration

### ISSUE THREAD

**Issue by filmaj** [magento/merchdocs#88]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/m2/ee/user_guide/cms/page-builder-media-image.html
From: `src/cms/page-builder-media-image.md`

## Description

- [ ] Update overview to describe manual upload vs. Adobe Stock
- [ ] Update procedures and screens to reflect changes to the UI

## Additional information

This should be assigned to the [Adobe Stock Integration Docs Project](https://github.com/magento/merchdocs/projects/6) and stems from #77. I am happy to take this one.

**Comment by bdenham** [comment]
This issue has been fixed with PR #192. Closing.
