### ISSUE TITLE
Clarify "Use system value" checkbox and why shipment notifications are not being sent

### ISSUE THREAD

**Issue by lollicupgithub** [magento/merchdocs#888]
Topic: ../sales/order-ship.html

Hi Magento Community,

We have Magento 2.3.4 version. 

1. What is the meaning of "use  system value " in store\configuration\sales\sales email\ shipment ?
![image](https://user-images.githubusercontent.com/36867251/100633156-90e73000-32e2-11eb-8819-76ef1992f98b.png)
We have customized the shipment template called "New shipment default".

2. We can manually send shipment notification to customer by pressing the send tracking number to customer. However, Magento won't auto send the shipment notification to customer by itself. Do you know why? Our order notification it will auto send order confirmation to customer  but not the shipment notification.
![image](https://user-images.githubusercontent.com/36867251/100633691-3d291680-32e3-11eb-86a4-50e34432480d.png)
![image](https://user-images.githubusercontent.com/36867251/100633899-79f50d80-32e3-11eb-8717-05e023ad21b1.png)
![image](https://user-images.githubusercontent.com/36867251/100633962-8d07dd80-32e3-11eb-8dae-cce3e93b67c2.png)

Kindly please assist to find out why shipment notification not sending to customer email.
Thank you.

frank.chan@karatpackaging.com 
mobile(909)263-8115

**Comment by ccondra** [comment]
Hi Lollicup -- The Use System Checkbox is used to override the default scope of individual configuration settings, and is explained in the [Changing Scope](https://docs.magento.com/user-guide/configuration/scope-change.html) topic. It's probably not practical to update individual topics, because it's used throughout the Magento configuration. However, I'll update a couple of topics to "connect the dots" better. When you can't find the answer to something, don't forget to try Search. Thanks for pointing this out!

**Comment by ccondra** [comment]
PR #980 addresses your question about the Use system value checkbox.  Your question about the shipment notification will have to be addressed as a separate PR. I don't know the answer, but will look into it.

**Comment by ccondra** [comment]
Hi Frank -- For shipment notifications, make sure that the transactional email for shipments is enabled and configured correctly for the store. See [Sales Emails](https://docs.magento.com/user-guide/marketing/sales-email-configure.html).  Customers can also track the status of their orders by [RSS feed](https://docs.magento.com/user-guide/sales/order-status-notification.html) if enabled in the configuration.  I hope this helps!  -- Claire

**Comment by lollicupgithub** [comment]
Thank you for your update. You can close the ticket. It is working fine. Thank you.
