### ISSUE TITLE
show shipping tax cost in summary

### ISSUE THREAD

**Issue by Eddcapone** [magento/merchdocs#889]
Topic:  ../tax/display-settings.html
I created a new shipping method for express shipping which costs 90€. How can I show the tax costs of the selected shipping method in the tax section, is there a setting in the backend?

Cart Summary:

[![show tax][1]][1]

  [1]: https://i.stack.imgur.com/bgxm6.png

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by dobooth** [comment]
I am going to close this as it does not appear to be a docs issue and I will assume they have the issue sorted by now.
