### ISSUE TITLE
Klarna setup docs incorrectly reference using Store View instead of Website

### ISSUE THREAD

**Issue by lazyguru** [magento/merchdocs#898]
# Topic clarification/correction request

## Topic Link

https://docs.magento.com/user-guide/payment/klarna-setup.html#step-2-configure-magento

## Description

The docs in this step say to switch to "Store View" however Klarna is not configurable at the store view level due to how Magento configures base currency and tax configuration (only available at the website level). Instead the docs should say to use the Website scope

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this
