### ISSUE TITLE
Price Rules information correction

### ISSUE THREAD

**Issue by mmansoor-magento** [magento/merchdocs#9]
# Background

Reported by Matthew Ferguson via email on 5/8/19:

Step 2, # 5 (last paragraph on the page after Apply a Price Rule to Multiple SKUs) on the following Magento 2 User Guide is obsolete:

https://docs.magento.com/m2/ee/user_guide/marketing/price-rule-multiple-sku.html

`Price rules are automatically processed with other system rules each night. When you create a new price rule, allow enough time for it to get into the system. Then, test the rule to make sure that it works correctly.`

Actual behavior:
When cron is running (recommended: every minute) and indexers are set to Update by Schedule, a catalog price rule will become active as soon as cron runs.

This was tested and confirmed on 2.2.7 by L3 developers Oleksander Rykh and Andrei Poltoratskyi. Price rules automatically processing with other system rules each night will only happen if cron is configured only to run once per night. If cron is not configured, then the price rule will not become active unless manual reindex is performed.`

## Affected docs

https://docs.magento.com/m2/ee/user_guide/marketing/price-rule-multiple-sku.html
Acceptance criteria

- [x] Open Source
- [x] Commerce
- [x] B2B

**Comment by filmaj** [comment]
I was playing around with this a little bit to try to figure out how to word the update in this issue appropriately. I looked into the [`cron` configuration](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html) and, if you follow the typical configuration instructions, the default `cron` configuration is set to update every minute. However, this could be customized to another value.

With that in mind, how should the doc update be structured, then? Should we link to the [`cron` configuration devdocs](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html), perhaps something like:

> Price rules are automatically processed with other system rules. How often this processing happens depends on your installation's [`cron` configuration](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-cron.html).

Compared to the current:

> Price rules are automatically processed with other system rules each night. When you create a new price rule, allow enough time for it to get into the system. Then, test the rule to make sure that it works correctly.

Happy to send a PR for this, let me know!

**Comment by filmaj** [comment]
I think this issue can be closed given #59 was merged.

**Comment by hellotaran** [comment]
@leslietilling As @filmaj commented this can be closed.

**Comment by leslietilling** [comment]
Thank you @hellotaran  and @filmaj
