### ISSUE TITLE
Clarify where your translations get stored

### ISSUE THREAD

**Issue by Eddcapone** [magento/merchdocs#902]
Topic:
../system/translate-inline.html

It does not explain where your translations are getting stored. For example how can I take the translations and apply them on another project?

**Comment by andrewbess** [comment]
@magento I am working on this

**Comment by hickskenh** [comment]
@andrewbess please advise if you are still working on this, or if we need to assign to another writer.  Thanks.

**Comment by hickskenh** [comment]
@andrewbess please advise if you are still working on this, or if we need to assign to another writer. Thanks.
