### ISSUE TITLE
Feedback on page: /system/frontend-development-workflow.html

### ISSUE THREAD

**Issue by nicpapakon** [magento/merchdocs#965]
When i did that my admin page crushed i my page get that: 

TypeError: Argument 1 passed to Magento\Framework\View\Page\Config\Renderer::canTypeBeFont() must be of the type string, null given, called in C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php on line 360 and defined in C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php:440 Stack trace: #0 C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php(360): Magento\Framework\View\Page\Config\Renderer->canTypeBeFont(NULL) #1 C:\xampp\htdocs\magento\vendor\magento\module-developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer.php(75): Magento\Framework\View\Page\Config\Renderer->addDefaultAttributes(NULL, ' rel="styleshee...') #2 C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php(423): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer->addDefaultAttributes(NULL, ' rel="styleshee...') #3 C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php(297): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml(Object(Magento\Framework\View\Asset\PropertyGroup)) #4 C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php(284): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup)) #5 C:\xampp\htdocs\magento\vendor\magento\module-developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer.php(87): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array) #6 C:\xampp\htdocs\magento\vendor\magento\framework\View\Page\Config\Renderer.php(137): Magento\Developer\Model\View\Page\Config\ClientSideLessCompilation\Renderer->renderAssets(Array) #7 C:\xampp\htdocs\magento\vendor\magento\framework\View\Result\Page.php(250): Magento\Framework\View\Page\Config\Renderer->renderHeadContent() #8 C:\xampp\htdocs\magento\vendor\magento\framework\View\Result\Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor)) #9 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #10 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array) #11 C:\xampp\htdocs\magento\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor)) #12 C:\xampp\htdocs\magento\generated\code\Magento\Framework\View\Result\Page\Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array) #13 C:\xampp\htdocs\magento\vendor\magento\framework\App\Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #14 C:\xampp\htdocs\magento\vendor\magento\framework\App\Bootstrap.php(263): Magento\Framework\App\Http->launch() #15 C:\xampp\htdocs\magento\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #16 {main}

**Comment by erikmarr** [comment]
Thank you for your feedback!  It's possible the documentation needs to be updated, but this looks like you need help resolving an error. To get answers to your questions, check the [Magento Support Knowledge Base](https://support.magento.com/), [forums](https://community.magento.com/), or [Stack Exchange](https://community.magento.com/). To report Magento 2 issues with code, see the [Magento 2 GitHub](https://github.com/magento/magento2). Thanks for taking the time to create a GitHub issue for docs improvement!

**Comment by dshevtsov** [comment]
@nicpapakon 
Thank you for taking on this issue. If you are still interested in working on this topic, please let us know your progress. Thanks for taking the time to help improve the documentation!

**Comment by depyou** [comment]
add 
`if(empty($this->getAssetContentType($asset))) var_dump($asset->getPath());`
 at vendor\magento\framework\View\Page\Config\Renderer.php below line:420;
find witch file can't getAssetContentType.
find add this file's xml;
Check the syntax for adding this file.
is YOU_MODULE::xxx/xxx.css or YOU_MODULE::xxx/xxx.js  
not YOU_MODULE/xxx/xxx.css or YOU_MODULE/xxx/xxx.js
must use `::` not `/`
