### ISSUE TITLE
Feedback on page: /cms/content-menu.html

### ISSUE THREAD

**Issue by Crissov** [magento/merchdocs#978]
The documentation of the 2.4+ [Media Gallery](https://docs.magento.com/user-guide/cms/media-gallery.html) claims that there should be a _Media > Media Gallery_ entry in the [Content Menu](https://docs.magento.com/user-guide/cms/content-menu.html) of the Admin Panel, but that's not mentioned nor pictured in its documentation.

**Comment by dineshvb** [comment]
@magento I am working on this
