### ISSUE TITLE
Re-examine the JSON file for Google Tag Manager on the linked page

### ISSUE THREAD

**Issue by swemagento** [magento/merchdocs#990]
Hi! 
So basically the json that you have for download gives me this error when I try to import it into google tag manager:

JSON-analysfel: extraneous input '2' expecting {'{', '['}

Page Link: https://docs.magento.com/user-guide/marketing/google-tag-manager.html

**Comment by dobooth** [comment]
When I check this, it validates properly with multiple validators.  Please let us know if there is a continuing issue with this.
