### ISSUE TITLE
Describe default behavior for storing old passwords

### ISSUE THREAD

**Issue by jeff-matthews** [magento/merchdocs#993]
Per @smiverma, the default Magento behavior is to store an Admin user's last four passwords to prevent them from being re-used when Admin users are forced to create a new password. This enhances password security policies.

We should add references to this default behavior in the following user guide topics:

- https://docs.magento.com/user-guide/stores/security-admin.html
- https://docs.magento.com/user-guide/customers/password-options.html

Proposed wording:

> Magento does not allow users to re-use their last four passwords.

**Comment by ccondra** [comment]
This PR is a duplicate of #1004 .
